checkupjs/checkup

- packages/cli/README.md
- packages/core/package.json
- packages/core/src/index.ts
- packages/core/src/types/index.ts
- packages/core/src/utils/get-config.ts
Add support for a consumer provided checkup config file, such as a .checkuprc, loaded via cosmiconfig. Add scaffolding to pass the checkup config to the
checkup task runner.
> feat(core): Add support for checkup config file

- packages/cli/__tests__/__snapshots__/index-test.ts.snap
- packages/cli/__tests__/index-test.ts
- packages/cli/src/index.ts
- packages/core/src/base-task.ts
- packages/core/src/file-searcher-task.ts
- packages/core/src/index.ts
- packages/core/src/task-list.ts
- packages/core/src/types/index.ts
- packages/core/src/utils/get-package-json.ts
- packages/plugin-ember/__tests__/__fixtures__/addon-package.json
- packages/plugin-ember/__tests__/__fixtures__/app-package.json
- packages/plugin-ember/__tests__/__snapshots__/dependencies-task-test.ts.snap
- packages/plugin-ember/__tests__/__snapshots__/project-info-task-test.ts.snap
- packages/plugin-ember/__tests__/__snapshots__/types-task-test.ts.snap
- packages/plugin-ember/__tests__/__utils__/ember-cli-fixturify-project.ts
- packages/plugin-ember/__tests__/dependencies-task-test.ts
- packages/plugin-ember/__tests__/project-info-task-test.ts
- packages/plugin-ember/__tests__/types-task-test.ts
- packages/plugin-ember/jest.config.js
- packages/plugin-ember/package.json
- packages/plugin-ember/src/tasks/dependencies-task.ts
- packages/plugin-ember/src/tasks/project-info-task.ts
- packages/plugin-ember/src/tasks/types-task.ts
- packages/plugin-ember/src/utils/project.ts
- yarn.lock
Checkup currently considers `process.cwd()` the base directory from which to run. In future cases, we want users to be able to run in a specific subdirectory. This PR adds support for a `path` argument. 
```shell
❯ checkup --help
A CLI that provides health check information about your project
USAGE
$ checkup PATH
ARGUMENTS
PATH  [default: .] The path referring to the root directory that Checkup will run in
OPTIONS
-f, --force
-h, --help       show CLI help
-s, --silent
-t, --task=task
-v, --version    show CLI version
--json
```
The path defaults to the current directory (`.`), with the ability for users to specify an alternate directory to run checkup in.
Addition: fixes broken tasks that were incorrectly testing the project's cwd instead of test fixture directories due to the lack of …
> Adding path argument to specify directory to run in

- package.json
- yarn.lock
This changes the top level build command to use `wsrun` instead of an unmanageable script config.
To run from the top level:
`yarn wsrun --stages build` will build all packages, in stages, starting from those that don't depend on other packages.
`yarn wsrun watch` will run `yarn watch` on every individual package, in parallel.
`yarn wsrun test` will run `yarn test` on every individual package, in parallel.
> Adding wsrun package to execute tasks in dependency order and parallel

- packages/cli/__tests__/__snapshots__/index-test.ts.snap
- packages/cli/__tests__/index-test.ts
- packages/core/package.json
- packages/core/src/types/index.ts
- packages/core/src/types/runtime-types.ts
- packages/core/src/utils/get-config.ts
- yarn.lock
Use io-ts to wrap CheckupConfig types so they can be accessed during
runtime and used to validate the configuration found via cosmiconfig
> Add Validation to Checkup Config

- package.json
- packages/cli/package.json
- packages/cli/src/index.ts
- packages/cli/src/parsers.ts
- packages/core/src/types/index.ts
- packages/parser-eslint/package.json
- packages/parser-eslint/src/eslint-parser.ts
- packages/parser-eslint/src/hooks/register-parsers.ts
- packages/parser-eslint/src/index.ts
- packages/parser-eslint/tsconfig.json
- yarn.lock
Adds `@checkup/parser-eslint` with `register-parsers` hook implementation. This hook registers the `eslint` parser, which is a bare-bones implementation of what we need for parsing eslint files.
> Adds @checkup/parser-eslint plugin package

- package.json
- packages/cli/__tests__/index-test.ts
- packages/cli/__tests__/priority-map-test.ts
- packages/cli/__tests__/task-list-test.ts
- packages/cli/src/priority-map.ts
- packages/cli/src/task-list.ts
- packages/core/src/base-task-result.ts
- packages/core/src/base-task.ts
- packages/core/src/index.ts
- packages/core/src/types/index.ts
- packages/plugin-default/src/hooks/register-tasks.ts
- packages/plugin-default/src/results/project-info-task-result.ts
- packages/plugin-default/src/tasks/project-info-task.ts
- packages/plugin-ember/src/hooks/register-tasks.ts
- packages/plugin-ember/src/results/dependencies-task-result.ts
- packages/plugin-ember/src/results/ember-project-task-result.ts
- packages/plugin-ember/src/results/types-task-result.ts
- packages/plugin-ember/src/tasks/dependencies-task.ts
- packages/plugin-ember/src/tasks/ember-project-task.ts
- packages/plugin-ember/src/tasks/types-task.ts
- packages/test-helpers/src/plugin.ts
This PR removes the multiple params passed in to `registerTask` when registering tasks via hooks.
> Refactoring task registration to simplify

- packages/cli/README.md
- packages/cli/__tests__/__snapshots__/index-test.ts.snap
- packages/cli/__tests__/index-test.ts
- packages/cli/src/index.ts
- packages/core/__tests__/configuration/get-filepath-loader-test.ts
- packages/core/src/configuration/loaders/get-filepath-loader.ts
- packages/core/src/configuration/loaders/get-search-loader.ts
- packages/core/src/index.ts
Add --config flag to checkup cli that allows users to optionally pass in
an explcit path to the config file to be loaded.
> Add config flag to optionally pass explicit config path to cli

- packages/cli/package.json
- packages/cli/src/helpers/pdf.ts
Fixes a bug in the PDF reporter where it errors if the `reportOutputPath` directory isn't created before trying to write the PDF to it.
> Fixing reportOutputPath to create directory if doesn't exist

- packages/cli/__tests__/__snapshots__/task-list-test.ts.snap
- packages/cli/__tests__/__utils__/mock-task-result.ts
- packages/cli/__tests__/index-test.ts
- packages/cli/__tests__/priority-map-test.ts
- packages/cli/__tests__/task-list-test.ts
- packages/cli/src/task-list.ts
- packages/core/src/base-task-result.ts
- packages/core/src/types/index.ts
- packages/plugin-default/src/tasks/project-info-task.ts
- packages/plugin-ember-octane/__tests__/results/octane-migration-status-tast-result-test.ts
- packages/plugin-ember-octane/src/results/octane-migration-status-task-result.ts
- packages/plugin-ember-octane/src/tasks/octane-migration-status-task.ts
- packages/plugin-ember/src/results/dependencies-task-result.ts
- packages/plugin-ember/src/tasks/dependencies-task.ts
- packages/plugin-ember/src/tasks/ember-project-task.ts
- packages/plugin-ember/src/tasks/types-task.ts
Cleanup. Encapsulates `taskName`, `friendlyTaskName`, and `taskClassification` in a `meta` property, similar to what is used in `BaseTaskResult`. Now, between tasks and task results, there's a standardized property, `meta`, which houses the meta data for a particular task.
> Add TaskMetaData to tasks

- packages/cli/__tests__/index-test.ts
In the "macOS-latest, 10" build, tests have been failing due to timeouts. Generally, after rerunning the tests, they pass.
It is mostly failing on the test that runs the checkup command. Increasing timeout for that test
> Increasing test timeout for test in @checkup/cli

- packages/cli/__tests__/tasks/checkup-meta-task-test.ts
- packages/cli/src/tasks/checkup-meta-task.ts
- packages/cli/tsconfig.json
- packages/cli/types/shorthash.d.ts
Fixes a bug when running checkup in dev mode - `ts-node` wasn't correctly reading the local `d.ts` files, and caused a build error when invoking a linked checkup. This PR removes the use of that module in favor of built-ins.
> Fixing checkup-meta-task's use of shorthash

- packages/cli/__tests__/generators/__snapshots__/generate-plugin-test.ts.snap
- packages/cli/templates/src/plugin/package.json.ejs
- packages/plugin-ember-octane/package.json
- packages/plugin-ember/package.json
- packages/test-helpers/src/plugin.ts
@lbdm44 found a bug in the published packages where the hooks paths were misconfigured (used `src` vs. `lib`). This PR fixes that.
> Fixing hooks config paths to point to lib vs src

- packages/cli/__tests__/__snapshots__/pdf-test.ts.snap
- packages/cli/__tests__/__snapshots__/task-list-test.ts.snap
- packages/cli/__tests__/commands/__snapshots__/run-test.ts.snap
- packages/cli/__tests__/commands/run-test.ts
- packages/cli/__tests__/generators/__snapshots__/generate-task-test.ts.snap
- packages/cli/__tests__/generators/generate-task-test.ts
- packages/cli/__tests__/pdf-test.ts
- packages/cli/__tests__/priority-map-test.ts
- packages/cli/__tests__/reporters-test.ts
- packages/cli/__tests__/task-list-test.ts
- packages/cli/src/generators/task.ts
- packages/cli/src/static/report-template.hbs
- packages/core/src/base-task-result.ts
- packages/core/src/types/index.ts
- packages/plugin-ember-octane/__tests__/results/__snapshots__/octane-migration-status-tast-result-test.ts.snap
- packages/plugin-ember-octane/src/tasks/octane-migration-status-task.ts
- packages/plugin-ember/__tests__/__snapshots__/dependencies-task-test.ts.snap
- packages/plugin-ember/__tests__/__snapshots__/ember-project-task-test.ts.snap
- packages/plugin-ember/__tests__/__snapshots__/types-task-test.ts.snap
- packages/plugin-ember/src/tasks/dependencies-task.ts
- packages/plugin-ember/src/tasks/ember-project-task.ts
- packages/plugin-ember/src/tasks/types-task.ts
Cleanup of `Category` enum.
- remove `Core`
- change `Core` tasks to Insights
- add `Recommended` category (to be used for future tasks)
> Removing Core category. Adding Recommendations and renaming Migration

- packages/cli/__tests__/__snapshots__/pdf-test.ts.snap
- packages/cli/__tests__/__utils__/render-partial.ts
- packages/cli/__tests__/report-components/numerical-card-test.ts
- packages/cli/src/static/components/numerical-card.hbs
- packages/cli/src/static/report-template.hbs
Implemented numerical-card and wrote tests. Added in support to render partials for tests as well, which will be used by other partials. Screenshot below shows numerical card in the grid populated with fake data.
> Implementing numerical-card

- packages/cli/__tests__/generators/__snapshots__/generate-plugin-test.ts.snap
- packages/cli/package.json
- packages/cli/templates/src/plugin/package.json.ejs
- packages/core/package.json
- packages/parser-eslint/package.json
- packages/plugin-ember-octane/package.json
- packages/test-helpers/package.json
This is a path to address the sporadic TS caching issues within tests. Ultimately, we would like to leverage TS directly and avoid the use of ts-jest.
> Adding --no-cache for jest tests to address test caching issues

- packages/cli/__tests__/commands/__snapshots__/run-test.ts.snap
- packages/cli/__tests__/commands/run-test.ts
- packages/cli/__tests__/task-list-test.ts
- packages/cli/src/commands/run.ts
- packages/cli/src/task-list.ts
The task flag was broken in that it would only run plugin-based tasks. This fix ensures it finds the correct task.
> Fixing `task` flag

- packages/cli/__tests__/__utils__/mock-task-result.ts
- packages/cli/__tests__/__utils__/render-partial.ts
- packages/cli/src/results/checkup-meta-task-result.ts
- packages/cli/src/results/project-meta-task-result.ts
- packages/core/src/types/index.ts
- packages/plugin-ember-octane/src/results/octane-migration-status-task-result.ts
- packages/plugin-ember/src/results/dependencies-task-result.ts
- packages/plugin-ember/src/results/ember-project-task-result.ts
- packages/plugin-ember/src/results/types-task-result.ts
Having `undefined` as an option for `ReportResultData` was causing problems as we needed to account for `ReportResultData` being undefined, which it never will, it was just put there as an temporary measure until we retrofitted all existing tasks to return some real data. I put in another bandaid here, ensuring that each task result returns some mock data for the pdf() hook, instead of allowing it to return undefined
> Removing `undefined` from `ReportResultData`, and adding mock results to all existing tasks

- packages/cli/__tests__/__utils__/mock-meta-task-result.ts
- packages/cli/__tests__/__utils__/mock-meta-task.ts
- packages/cli/__tests__/__utils__/mock-task-result.ts
- packages/cli/__tests__/reporters-test.ts
- packages/cli/src/base-meta-task-result.ts
- packages/cli/src/commands/run.ts
- packages/cli/src/generators/task.ts
- packages/cli/src/meta-task-list.ts
- packages/cli/src/reporters.ts
- packages/cli/src/results/checkup-meta-task-result.ts
- packages/cli/src/results/project-meta-task-result.ts
- packages/cli/src/tasks/checkup-meta-task.ts
- packages/cli/src/tasks/project-meta-task.ts
- packages/cli/src/types/index.ts
- packages/core/src/types/tasks.ts
- packages/core/src/utils/task-result-comparator.ts
As discussed, we needed to split the meta tasks out to a separate data structure and make them private. This change adds a separate `MetaTaskList` that operates on `MetaTask`s, and return `MetaTaskResult`s.
> Removing meta category. Making meta tasks internal

- packages/checkup-plugin-ember-octane/__tests__/results/__snapshots__/octane-migration-status-tast-result-test.ts.snap
- packages/checkup-plugin-ember-octane/src/tasks/octane-migration-status-task.ts
- packages/cli/__tests__/__snapshots__/reporters-test.ts.snap
- packages/cli/__tests__/__utils__/mock-pie-chart-task-result.ts
- packages/cli/__tests__/pdf-test.ts
- packages/cli/__tests__/report-components/numerical-card-test.ts
- packages/cli/__tests__/report-components/pie-chart-test.ts
- packages/cli/__tests__/report-components/table-test.ts
- packages/cli/__tests__/reporters-test.ts
- packages/cli/src/helpers/pdf.ts
- packages/cli/src/reporters.ts
- packages/cli/static/components/numerical-card.hbs
- packages/cli/static/components/pie-chart.hbs
- packages/cli/static/components/table.hbs
- packages/cli/static/report-template.hbs
- packages/core/src/types/tasks.ts
- packages/plugin-ember/__tests__/__snapshots__/dependencies-task-test.ts.snap
- packages/plugin-ember/__tests__/__snapshots__/ember-project-task-test.ts.snap
- packages/plugin-ember/__tests__/__snapshots__/types-task-test.ts.snap
- packages/plugin-ember/src/tasks/dependencies-task.ts
- packages/plugin-ember/src/tasks/ember-project-task.ts
- packages/plugin-ember/src/tasks/types-task.ts
Previously, there was a PR that went in that flattened the data structure of the results. While that works well for the JSON results, the PDF results need a bit more shape/structure so we can iterate over the different categories and priorities separately. This is useful so we can have a different section per each category and type. So basically reverted the flattening change for the pdf flow, changes the hbs files so we can render the different sections based on the new data format, and added some useful types to remove the `any` around the results coming into the pdf flow to keep things robust moving forward 
Note - none of the UI being generated right now is "to spec" - just a bunch of partials inside some section boxes with titles.
> Splitting out pdf results into sections

- .github/workflows/ci-build.yml
We have pinned node to 12 via volta in this app, and node 10 will only be supported until 5/19. Since we are still in prerelease, and have pinned node, removing node 10 from our testing matrix
> Removing node 10 from our CI test flow

- packages/checkup-plugin-ember-octane/package.json
- packages/checkup-plugin-ember-octane/src/tasks/octane-migration-status-task.ts
- packages/core/package.json
- packages/core/src/types/parsers.ts
Core didn't have direct dependencies on `eslint` and `ember-template-lint`, even though it required them. It was getting these dependencies via `checkup-plugin-ember-octane`. This PR removes the dependencies from the latter package to the former. Additionally, it fixes the types in the latter package to not require direct dependencies.
> Fixing missing dependencies in core

- packages/checkup-plugin-ember-octane/__tests__/results/__snapshots__/octane-migration-status-tast-result-test.ts.snap
- packages/checkup-plugin-ember-octane/__tests__/results/octane-migration-status-tast-result-test.ts
- packages/checkup-plugin-ember-octane/src/results/octane-migration-status-task-result.ts
- packages/checkup-plugin-ember/__tests__/__snapshots__/dependencies-task-test.ts.snap
- packages/checkup-plugin-ember/__tests__/__snapshots__/ember-project-task-test.ts.snap
- packages/checkup-plugin-ember/__tests__/__snapshots__/types-task-test.ts.snap
- packages/checkup-plugin-ember/__tests__/dependencies-task-test.ts
- packages/checkup-plugin-ember/__tests__/ember-project-task-test.ts
- packages/checkup-plugin-ember/__tests__/types-task-test.ts
- packages/checkup-plugin-ember/src/results/dependencies-task-result.ts
- packages/checkup-plugin-ember/src/results/ember-project-task-result.ts
- packages/checkup-plugin-ember/src/results/types-task-result.ts
- packages/cli/__tests__/__snapshots__/reporters-test.ts.snap
- packages/cli/__tests__/__utils__/mock-pie-chart-task-result.ts
- packages/cli/__tests__/__utils__/mock-task-result.ts
- packages/cli/__tests__/commands/run-test.ts
- packages/cli/__tests__/generators/__snapshots__/generate-task-test.ts.snap
- packages/cli/__tests__/pdf-test.ts
- packages/cli/__tests__/reporters-test.ts
- packages/cli/src/helpers/ui-report.ts
- packages/cli/src/reporters.ts
- packages/cli/templates/src/task/src/results/task-result.js.ejs
- packages/cli/templates/src/task/src/results/task-result.ts.ejs
- packages/core/src/types/tasks.ts
We will now be targeting an html report as our MVP to allow for more interactivity. Changing all existing tasks to use html hook, but leaving pdf infra in place so we can use after MVP is complete
> Adding html as a reporter type, and replacing all pdf() calls with html()

- packages/checkup-plugin-ember-octane/__tests__/results/octane-migration-status-tast-result-test.ts
- packages/checkup-plugin-ember-octane/src/results/octane-migration-status-task-result.ts
- packages/checkup-plugin-ember/__tests__/ember-dependencies-task-test.ts
- packages/checkup-plugin-ember/__tests__/ember-types-task-test.ts
- packages/checkup-plugin-ember/src/results/ember-dependencies-task-result.ts
- packages/checkup-plugin-ember/src/results/ember-types-task-result.ts
- packages/cli/__tests__/__utils__/mock-meta-task-result.ts
- packages/cli/__tests__/__utils__/mock-pie-chart-task-result.ts
- packages/cli/__tests__/__utils__/mock-task-result.ts
- packages/cli/__tests__/generators/__snapshots__/generate-task-test.ts.snap
- packages/cli/__tests__/meta-task-list-test.ts
- packages/cli/__tests__/task-list-test.ts
- packages/cli/__tests__/tasks/checkup-meta-task-test.ts
- packages/cli/__tests__/tasks/project-meta-task-test.ts
- packages/cli/src/reporters.ts
- packages/cli/src/results/checkup-meta-task-result.ts
- packages/cli/src/results/project-meta-task-result.ts
- packages/cli/src/types/index.ts
- packages/cli/templates/src/task/__tests__/task.js.ejs
- packages/cli/templates/src/task/__tests__/task.ts.ejs
- packages/cli/templates/src/task/src/results/task-result.js.ejs
- packages/cli/templates/src/task/src/results/task-result.ts.ejs
- packages/core/src/types/tasks.ts
Renames the following methods in the `TaskResult` interface:
- `stdout` -> `toConsole`
- `json` -> `toJson`
- `html` -> `toResultData`
> Renaming task result methods

- package.json
- packages/cli/README.md
- packages/cli/package.json
- packages/cli/src/commands/generate.ts
- packages/cli/src/generators/base-generator.ts
- packages/cli/src/generators/config.ts
- packages/cli/src/generators/plugin.ts
- packages/cli/src/generators/task.ts
- packages/core/__tests__/configuration/__snapshots__/checkup-config-service-test.ts.snap
- packages/core/__tests__/configuration/cosmiconfig-service-test.ts
- packages/core/__tests__/configuration/get-initialization-loader-test.ts
- packages/core/package.json
- packages/core/src/configuration/checkup-config-service.ts
- packages/core/src/configuration/cosmiconfig-service.ts
- packages/core/src/types/configuration.ts
- yarn.lock
Standardizing the format that one sees when running each of the three generators.
Now, the output will print a consistent message for what action is about to occur
Generating config:
```
❯ checkup generate config
Generating checkup config (checkup v0.0.10)
? What format do you want your config file to be in? JSON
create .checkuprc
```
Generating plugin:
```
❯ checkup generate plugin fake
Generating checkup-plugin-fake (checkup v0.0.10)
? TypeScript Yes
? Description Checkup plugin
? Author
? Repository
create src/index.ts
create src/hooks/register-tasks.ts
create src/types/index.ts
create __tests__/.gitkeep
create src/results/.gitkeep
create src/tasks/.gitkeep
create jest.config.js
create tsconfig.json
create package.json
create README.md
```
Generating task:
```
❯ checkup generate task …
```
> Standardizing output from generators

- packages/cli/__tests__/__utils__/run-command.ts
- packages/cli/__tests__/commands/run-test.ts
- packages/test-helpers/package.json
Adding new `runCommand` method to correctly invoke commands in tests.
> Fixing command tests

- packages/cli/__tests__/__utils__/mock-meta-task-result.ts
- packages/cli/__tests__/commands/__snapshots__/run-test.ts.snap
- packages/cli/__tests__/tasks/checkup-meta-task-test.ts
- packages/cli/__tests__/tasks/project-meta-task-test.ts
- packages/cli/src/reporters.ts
- packages/cli/src/results/checkup-meta-task-result.ts
- packages/cli/src/results/project-meta-task-result.ts
- packages/cli/src/types/index.ts
Adds an `outputPosition` prop to meta task results, allow us to specify where the meta task is output to.
> Add ability to specify location of output for meta tasks

- CONTRIBUTING.md
- packages/checkup-plugin-ember-octane/README.md
- packages/cli/README.md
- packages/cli/src/commands/run.ts
- packages/cli/src/index.ts
When we swapped to a multi-command, we lost the ability to invoke checkup without having to specify a subcommand. This PR restores that ability.
Before:
```shell
checkup run PATH
```
After:
```shell
checkup PATH
```
> Changes `checkup run` to default to `checkup` (without `run`)

- packages/checkup-plugin-ember-octane/__tests__/tasks/octane-migration-status-task-test.ts
- packages/checkup-plugin-ember-octane/src/tasks/octane-migration-status-task.ts
- packages/checkup-plugin-ember/__tests__/ember-dependencies-task-test.ts
- packages/checkup-plugin-ember/__tests__/ember-in-repo-addons-engines-task-test.ts
- packages/checkup-plugin-ember/__tests__/ember-types-task-test.ts
- packages/checkup-plugin-ember/src/tasks/ember-dependencies-task.ts
- packages/checkup-plugin-ember/src/tasks/ember-in-repo-addons-engines-task.ts
- packages/cli/README.md
- packages/cli/__tests__/commands/run-error-test.ts
- packages/cli/__tests__/commands/run-test.ts
- packages/cli/__tests__/generators/__snapshots__/generate-task-test.ts.snap
- packages/cli/__tests__/tasks/checkup-meta-task-test.ts
- packages/cli/__tests__/tasks/outdated-dependencies-task-test.ts
- packages/cli/__tests__/tasks/project-meta-task-test.ts
- packages/cli/src/commands/run.ts
- packages/cli/src/tasks/outdated-dependencies-task.ts
- packages/cli/src/tasks/project-meta-task.ts
- packages/cli/templates/src/task/__tests__/task.js.ejs
- packages/cli/templates/src/task/__tests__/task.ts.ejs
- packages/core/__tests__/base-task-test.ts
- packages/core/src/file-searcher-task.ts
- packages/core/src/types/cli.ts
- packages/test-helpers/src/get-task-context.ts
As discussed in [this issue](https://github.com/checkupjs/checkup/issues/400), we are going to be using `--cwd` as an optional flag (defaulting to `'.'`) to pass in the root directory, so the paths command line args can represent paths/globs for checkup to operate on. This PR just moves the paths arg to `--cwd`
> Changing the run command arg so that the root directory is passed in via flag, so args can be used for paths to operate on

- packages/cli/README.md
- packages/cli/__tests__/commands/run-test.ts
- packages/cli/__tests__/reporters-test.ts
- packages/cli/src/commands/run.ts
- packages/cli/src/helpers/ui-report.ts
- packages/cli/src/reporters.ts
- packages/core/__tests__/base-task-test.ts
- packages/core/src/types/cli.ts
- packages/core/src/types/tasks.ts
- packages/test-helpers/src/get-task-context.ts
This is primarily a flags cleanup PR. I've done the following:
1. Removed the `silent` option (for now, it wasn't working anyway!)
1. Removed the `force` option (wasn't used)
1. Renamed `reporter` to `format`
1. Renamed `reportOutputDir` to `outputFile`, and made it accept a file path instead
The main change is the last one, and I've added the ability to output both HTML and JSON. You can now do the following:
- `checkup -f <format>` - will output to stdout
- `checkup -f <format> -o '{default}.<format>' - will output using the default name format (example: `checkup-report-2020-05-18-14_56_19.<format>`)
- `checkup -f <format> -o my-file.<format>` - will output using the specified name to the `cwd`
- `checkup -f <format> -o /absolute/my-file.<format>` - will output using the absolute path
> Standardize flags

- packages/checkup-plugin-ember/__tests__/ember-dependencies-task-test.ts
- packages/checkup-plugin-ember/src/tasks/ember-dependencies-task.ts
- packages/checkup-plugin-ember/src/tasks/ember-in-repo-addons-engines-task.ts
- packages/checkup-plugin-ember/src/utils/project.ts
- packages/cli/__tests__/tasks/outdated-dependencies-task-test.ts
- packages/cli/__tests__/tasks/project-meta-task-test.ts
- packages/cli/src/commands/run.ts
- packages/cli/src/helpers/get-package-json.ts
- packages/cli/src/tasks/outdated-dependencies-task.ts
- packages/cli/src/tasks/project-meta-task.ts
- packages/core/__tests__/base-task-test.ts
- packages/core/src/index.ts
- packages/core/src/types/tasks.ts
- packages/test-helpers/src/get-task-context.ts
This is a part of https://github.com/checkupjs/checkup/issues/400.
Also removing getPackageJson from core, so it isnt made available to the plugins, as they shouldnt need to use it.
The one task that is still implemented questionably is `ember-in-repo-addons-engines-task` - it reads all package.jsons in a repo, I think it should likely still just operate from root, and traverse and find all package.jsons, but I will revisit that implementation when I add in support for the globs
> Adding pkg: PackageJson to the TaskContext and updating all tasks to use it

- packages/checkup-plugin-ember/__tests__/ember-in-repo-addons-engines-task-test.ts
We have been seeing sporadic failures in tests where the JSON results from ember-in-repo-addons-engines-task-test have been coming back in random order. Sorting them in the test so this wont happen anymore
> Sorting JSON results for ember-in-repo-addons-engines-task-test

- packages/checkup-plugin-ember-octane/src/tasks/octane-migration-status-task.ts
- packages/checkup-plugin-ember/src/tasks/ember-in-repo-addons-engines-task.ts
- packages/checkup-plugin-ember/src/tasks/ember-test-types-task.ts
- packages/checkup-plugin-ember/src/tasks/ember-types-task.ts
- packages/cli/package.json
- packages/cli/src/commands/run.ts
- packages/cli/src/tasks/eslint-disable-task.ts
- packages/cli/src/tasks/lines-of-code-task.ts
- packages/core/__tests__/utils/file-paths-array-test.ts
- packages/core/__tests__/utils/get-paths-test.ts
- packages/core/src/index.ts
- packages/core/src/types/tasks.ts
- packages/core/src/utils/file-paths-array.ts
- packages/core/src/utils/get-paths.ts
- packages/test-helpers/src/checkup-fixturify-project.ts
- packages/test-helpers/src/get-task-context.ts
Many of the tasks were taking the paths string[] from TaskContext and using micromatch to filter by globs. Now, the paths object in TaskContext is of type FilePaths which extends array and adds function filterByGlob, to make it easier for task authors to filter the file paths array. This obscures the implementation detail of using micromatch to authors.
> Creating FilePathsArray class that extends array and offers filtering functionality

- packages/cli/__tests__/commands/__snapshots__/run-test.ts.snap
- packages/cli/__tests__/tasks/lines-of-code-task-test.ts
- packages/cli/src/tasks/lines-of-code-task.ts
- packages/core/__tests__/utils/get-paths-test.ts
- packages/core/package.json
- packages/core/src/utils/get-paths.ts
Previously, we were taking all "extensions" and using them to call sloc. Extensions were defined as a string after a period. However, when running this on a real app, there was a ton of random garbage getting thrown in there. I decided to just use the exensions supported by sloc, and just add
two additional (json and md). This fits our current use case, and we can re-evaluate (also re-evaluate using this subpar library) if things change and it no longer fits our use case.
> (bug fix) Restricting file types for LOC class

- packages/cli/__tests__/commands/run-error-test.ts
- packages/cli/__tests__/commands/run-test.ts
- packages/cli/src/index.ts
- packages/cli/src/run-command.ts
Usage:
```javascript
let checkup = require('@checkup/cli');
checkup
.runCommand(['run', '--format', 'json', '--cwd', '.'])
.catch(require('@oclif/errors/handle'));
```
> Externalizing programmatic invocation of checkup

- packages/checkup-plugin-ember-octane/__tests__/results/__snapshots__/octane-migration-status-tast-result-test.ts.snap
- packages/checkup-plugin-ember/__tests__/__snapshots__/ember-dependencies-task-test.ts.snap
- packages/checkup-plugin-ember/__tests__/__snapshots__/ember-in-repo-addons-engines-task-test.ts.snap
- packages/checkup-plugin-ember/__tests__/__snapshots__/ember-test-type-task-test.ts.snap
- packages/checkup-plugin-ember/__tests__/__snapshots__/ember-types-task-test.ts.snap
- packages/checkup-plugin-ember/__tests__/template-lint-disable-task-test.ts
- packages/checkup-plugin-ember/src/results/template-lint-disable-task-result.ts
- packages/checkup-plugin-javascript/__tests__/__snapshots__/outdated-dependencies-task-test.ts.snap
- packages/checkup-plugin-javascript/__tests__/eslint-disable-task-test.ts
- packages/checkup-plugin-javascript/__tests__/eslint-summary-task-test.ts
- packages/checkup-plugin-javascript/src/results/eslint-disable-task-result.ts
- packages/cli/__tests__/commands/__snapshots__/run-test.ts.snap
- packages/cli/__tests__/reporters-test.ts
- packages/cli/__tests__/tasks/lines-of-code-task-test.ts
- packages/cli/src/reporters.ts
- packages/cli/src/tasks/lines-of-code-task.ts
- packages/core/src/types/tasks.ts
- packages/core/src/utils/ui.ts
In a previous PR, I added the concept of a string `category` to checkup, and sorted the results by category. In this PR, I actually render the category to stdout for each group as a header (bold, with the `===` before and after the string), and changed the task headers to not render the `===`, making them more sort of subheaders.
Attached before and after to help show the UI changes.
> Render the task category in stdout

- packages/checkup-plugin-ember/__tests__/__snapshots__/ember-dependencies-task-test.ts.snap
- packages/core/package.json
- packages/core/src/utils/data-transformers.ts
- types/startcase.d.ts
- yarn.lock
There were two versions of "startcase" in the repo - lodash's and https://www.npmjs.com/package/startcase. Removing the latter in favor of lodash
> Removing startcase library from checkup

- packages/core/__tests__/base-task-test.ts
- packages/core/src/base-task.ts
- packages/core/src/types/config.ts
As tasks are always 'on' by default, there is no reason to have a config option to turn them on. If that changes, we will add this option back in. This change aligns with how the ActionConfig works
> Removing 'on' option from task config because tasks are always on by default

- packages/cli/__tests__/__utils__/generate-plugin.ts
- packages/cli/__tests__/generators/__snapshots__/generate-config-test.ts.snap
- packages/cli/__tests__/generators/__snapshots__/generate-plugin-test.ts.snap
- packages/cli/__tests__/generators/__snapshots__/generate-task-test.ts.snap
- packages/cli/__tests__/generators/generate-config-test.ts
- packages/cli/__tests__/generators/generate-plugin-test.ts
- packages/cli/__tests__/generators/generate-task-test.ts
- packages/cli/src/commands/generate.ts
- packages/cli/src/generators/base-generator.ts
Fixes generators to correctly generate in a specified path. Changes the path arg to a flag.
```bash
checkup generate config --path ./lib
```
TODO:
> Ensuring generators can generate into a specific path

- packages/cli/__tests__/commands/__snapshots__/run-test.ts.snap
- packages/cli/__tests__/tasks/project-meta-task-test.ts
- packages/cli/src/results/project-meta-task-result.ts
- packages/cli/src/tasks/project-meta-task.ts
- packages/core/src/utils/get-paths.ts
If checkup is run on a subset of the files in an app, reflect that in the report. 
Examples: 
```
➜  travis-web git:(checkup) checkup '**/app**'
Checkup report generated for travis v0.0.1 (14 files analyzed)
This project is 8 years old, with 1380 active days, 5870 commits and 1538 files.
```
```
➜  travis-web git:(checkup) checkup
Checkup report generated for travis v0.0.1
This project is 8 years old, with 1380 active days, 5870 commits and 1538 files.
```
> Adding count of files checkup operated on to the project-meta task

- packages/checkup-plugin-ember/__tests__/ember-test-type-task-test.ts
- packages/checkup-plugin-javascript/__tests__/eslint-summary-task-test.ts
- packages/core/__tests__/action-list-test.ts
- packages/core/__tests__/base-task-test.ts
- packages/core/__tests__/config-test.ts
- packages/core/src/action-list.ts
- packages/core/src/base-task.ts
- packages/core/src/config/index.ts
- packages/core/src/index.ts
- packages/core/src/types/config.ts
This PR adds a specific type to represent the common config value pattern we use:
```typescript
type ConfigValue<T extends {}> = 'on' | 'off' | ['on' | 'off', T];
```
This allows us to better represent this common pattern when used in code.
Additionally, I've added a method to handle the common parsing of this type of value:
```typescript
function getConfigTuple<T>(configValue: ConfigValue<T> | undefined): [boolean, T]
```
This allows us to parse the config tuple in a consistent manner, without repeating our code everywhere.
**Note**: This reverses changes to some of the types we made recently, namely the removal of the `'on'` value in config. This is mainly to allow for us to release new tasks/actions etc without having them explicitly enabled. A future PR will introduce the concept of …
> Adds a specific type for a config value

- packages/cli/__tests__/generators/__snapshots__/generate-task-test.ts.snap
- packages/cli/src/commands/run.ts
- packages/cli/src/reporters/console-reporter.ts
- packages/cli/templates/src/task/src/tasks/task.js.ejs
- packages/cli/templates/src/task/src/tasks/task.ts.ejs
- packages/core/src/actions/registered-actions.ts
- packages/core/src/index.ts
- packages/core/src/task-reporters/registered-task-reporters.ts
- packages/core/src/types/tasks.ts
In order to support backwards compatibility while we move towards component-based console output, and to support any power-user use cases for reporting, we're adding support for registering and defining your own task reporter. Reporters are registered for that task only, and are looked up via `TaskName`.
> Adding ability to register custom console reporter

- packages/cli/bin/run
- packages/cli/package.json
- yarn.lock
Benchmarking shows a 7.33x improvement in CLI performance by adding `v8-compile-cache`.
```shell
❯ hyperfine 'DISABLE_V8_COMPILE_CACHE=1 ./bin/checkup' './bin/checkup' --ignore-failure
Benchmark #1: DISABLE_V8_COMPILE_CACHE=1 ./bin/checkup
Time (mean ± σ):       0.3 ms ±   1.0 ms    [User: 0.0 ms, System: 0.2 ms]
Range (min … max):     0.0 ms …  10.5 ms    504 runs
Warning: Command took less than 5 ms to complete. Results might be inaccurate.
Warning: Ignoring non-zero exit code.
Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet PC without any interferences from other programs. It might help to use the '--warmup' or '--prepare' options.
Benchmark #2: ./bin/checkup
Time (mean ± σ):       0.2 ms ±   0.7 ms    [User: 0.0 ms, System: 0.1 ms]
Range (min …
```
> task: Adding v8-compile-cache to speed up CLI perf

- packages/core/package.json
`@checkup/core` was missing a direct dependency on `recast`. Added now.
> Adding missing dependency

- packages/cli/__tests__/generators/__snapshots__/generate-actions-test.ts.snap
- packages/cli/__tests__/generators/generate-actions-test.ts
- packages/cli/src/commands/generate.ts
- packages/cli/src/generators/actions.ts
- packages/cli/src/generators/base-generator.ts
- packages/cli/src/generators/plugin.ts
- packages/cli/src/generators/task.ts
- packages/cli/templates/src/actions/src/actions/actions.js.ejs
- packages/cli/templates/src/actions/src/actions/actions.ts.ejs
- packages/cli/templates/src/actions/src/hooks/register-actions.js.ejs
- packages/cli/templates/src/actions/src/hooks/register-actions.ts.ejs
Allows for generating actions hooks and associated actions files.
```shell
❯ checkup generate actions my-foo
Generating my-foo-actions (checkup v0.3.2)
? TypeScript Yes
? Enter the task name that these actions will be associated with (the string value in the taskName property of the task class)
. foo
conflict src/hooks/register-actions.ts
? Overwrite src/hooks/register-actions.ts? overwrite
force src/hooks/register-actions.ts
create src/actions/my-foo-actions.ts
```
> Adding actions generator

- packages/core/src/utils/ui.ts
When people have light terminal themes, they cant see chalk.white
> Remove chalk.white from terminal output

- packages/cli/src/commands/run.ts
- packages/core/src/index.ts
- packages/core/src/utils/get-paths.ts
The UI is frozen when running the CLI, which gives the impression that things are stalled. This defeats the entire purpose of the UI spinner, which is supposed to indicate that work is in progress.
Adding a worker thread for the walkSync where we expand globs helps with this.
> Getting paths in CLI via threads

- packages/cli/__tests__/commands/__snapshots__/run-test.ts.snap
- packages/cli/__tests__/commands/run-test.ts
- packages/core/src/base-task.ts
Currently, if a task `foo` is set to "off" in config, but checkup is run via `checkup --task foo` the task doesnt run. The command line args override config for excludepaths, and it should work the same way for tasks. Now, if a task is passed in via command line arg, it will always run, regardless of config value
> Prioritizing cli args for turning tasks on

- packages/checkup-plugin-javascript/__tests__/__snapshots__/eslint-summary-task-test.ts.snap
- packages/checkup-plugin-javascript/__tests__/eslint-summary-task-test.ts
- packages/checkup-plugin-javascript/src/tasks/eslint-summary-task.ts
There was a bug in eslint-summary task where it was linting all files, not just the paths passed in
> [bugfix] Fixing eslint-summary task so it only lints files passed in

- packages/cli/__tests__/commands/__snapshots__/run-test.ts.snap
- packages/cli/__tests__/tasks/project-meta-task-test.ts
- packages/cli/src/commands/run.ts
- packages/cli/src/get-checkup-result.ts
- packages/cli/src/reporters/console-reporter.ts
- packages/cli/src/reporters/json-reporter.ts
- packages/cli/src/results/project-meta-task-result.ts
- packages/cli/src/tasks/project-meta-task.ts
- packages/cli/src/types/index.ts
- packages/core/src/types/checkup-result.ts
Some cleanup around the result type. There were some misalignments with the `CheckupResult` and the actual output. This change cleans that up, and fixes some oddly named output properties.
> Fixing checkup-result types and ensuring results use typed output

- packages/checkup-plugin-ember/src/tasks/ember-test-types-task.ts
Bug in ember-test-types is triggered when a test file has `// eslint-disable-next-line` with a rule that our eslint parser doesnt have. Previously, it assumed that the message is going to contain results from the test-type rule but when eslint encounters a disable like that it  will throw an error w message
```
message: "Definition for rule '@linkedin/pemberly/disallow-classnames-in-assertions' was not found."
```
filtered lint results to ensure we are only looking at the data we want here
> Bug fix for ember-test-types-task

- packages/checkup-plugin-javascript/__tests__/eslint-disable-task-test.ts
- packages/checkup-plugin-javascript/src/tasks/eslint-disable-task.ts
Using babel parse/traverse requires us to configure the babel plugins manually. Recast already does this automatically, so switching back to using that.
> Fixing eslint-disable-task to use recast (with correct babel plugins) vs. raw babel

- packages/checkup-plugin-javascript/package.json
https://github.com/checkupjs/checkup/pull/651
^^ this introduced a dependency on @babel/parser but didnt add it to package.json
When running the eslint-disables task now, it throws an error :
```
Taskname        Error
eslint-disables Cannot find module 'recast/parsers/babel'
Require stack:
- /Users/ckessler/voyager-web_trunk/node_modules/checkup-plugin-javascript/lib/tasks/eslint-disable-task.js
- /Users/ckessler/voyager-web_trunk/node_modules/checkup-plugin-javascript/lib/hooks/register-tasks.js
- /Users/ckessler/voyager-web_trunk/node_modules/@oclif/config/lib/config.js
- /Users/ckessler/voyager-web_trunk/node_modules/@oclif/config/lib/index.js
- /Users/ckessler/voyager-web_trunk/node_modules/@oclif/command/lib/command.js
- /Users/ckessler/voyager-web_trunk/node_modules/@oclif/command/li …
```
> Fixing missing dep in checkup-plugin-javascript

- packages/core/src/utils/ui.ts
Previously, the colors that rendered the graphs were being incremented by 1 in a color palette. this led to the colors often not being visually distinct. fixed that by incrementing colors by 3
Before (hard to distinguish between greens on the graph) 
After
> Ensuring colors in graphs are visually distinct

- packages/cli/__tests__/generators/__snapshots__/generate-task-test.ts.snap
- packages/cli/__tests__/generators/generate-task-test.ts
- packages/cli/__tests__/task-list-test.ts
- packages/cli/package.json
- packages/cli/src/meta-task-list.ts
- packages/cli/src/reporters/console-reporter.ts
- packages/cli/src/task-list.ts
- packages/core/src/types/tasks.ts
The console error output, when a task throws an error, only contained the error message. This change extends that to include the error stack, which allows for easier debugging of failing tasks.
Implements #522
> Extends error output to include stack traces

- packages/cli/__tests__/commands/run-error-test.ts
- packages/cli/__tests__/commands/run-test.ts
- packages/cli/package.json
- packages/cli/src/run-command.ts
- types/stdout-monkey.d.ts
- yarn.lock
The current (albeit rudamentary) Node API's `runCommand` function doesn't return stdout, so doesn't 'feel' like a real API. This PR fixes that so that it correctly returns a value. 
This is effectively a temporary solution to enable the Node API until a full refactor can take place. There are non-trivial issues to address with a refactor, as there's some tight coupling with oclif's APIs.
> Fixes node API to return stdout from runCommand

- packages/checkup-plugin-ember/__tests__/__snapshots__/ember-dependencies-task-test.ts.snap
- packages/cli/src/reporters/console-reporter.ts
- packages/core/src/data/builders.ts
`consoleMessage` is what renders to the console when there are 0 results of a check. This was at `message.properties.consoleMessage` for some of the builders, but not the others. Moving all to `properties.consoleMessage` for consistency with reporters
> Moving consoleMessage to properties

- package.json
- packages/cli/src/commands/run.ts
- packages/core/__tests__/__fixtures__/.checkuprc.json
- packages/core/__tests__/config-test.ts
- packages/core/jest.config.js
- packages/core/package.json
- packages/core/src/config.ts
- packages/core/src/index.ts
- yarn.lock
This PR adds support to load configs from HTTP endpoints.
```shell
checkup --config http://my-config-endpoint ...
```
Related to https://github.com/checkupjs/rfcs/pull/3
> Adding HTTP support for config loading

- packages/cli/__tests__/__snapshots__/checkup-node-api-test.ts.snap
- packages/cli/__tests__/checkup-node-api-test.ts
- packages/cli/__tests__/commands/__snapshots__/run-test.ts.snap
- packages/cli/__tests__/commands/run-test.ts
- packages/cli/__tests__/generators/__snapshots__/generate-task-test.ts.snap
- packages/cli/__tests__/generators/generate-task-test.ts
- packages/cli/package.json
- packages/cli/src/commands/run.ts
- packages/cli/src/index.ts
- packages/cli/src/run-command.ts
- types/stdout-monkey.d.ts
The stop-gap API implemented in (#705) is superseded by this PR. This uses the standard APIs that oclif provides, and allows for correct invocation of Checkup via node.
TODO
> Implements new node API to allow for programmatic invocation of Checkup

- packages/cli/src/reporters/json-reporter.ts
Since we're now outputting fully compliant SARIF format, we should save to a file with a `.sarif` extension vs. JSON, since native SARIF readers will recognize this extension.
> Changes file extension of outputFile to sarif

- packages/cli/src/index.ts
Usage:
```ts
import { getReporter } from '@checkup/cli';
import { OutputFormat } from '@checkup/core';
//...
let result = await Checkup.run([\\...]);
let reporter = getReporter(OutputFormat.stdout);
reporter.report();
```
> Exporting getReporters API in order to provide reporting for Node API

- package.json
- packages/checkup-plugin-ember/src/tasks/ember-template-lint-disable-task.ts
- packages/checkup-plugin-javascript/src/tasks/eslint-disable-task.ts
- packages/cli/__tests__/__snapshots__/checkup-node-api-test.ts.snap
- packages/cli/__tests__/commands/__snapshots__/run-test.ts.snap
- packages/cli/__tests__/generators/__snapshots__/generate-config-test.ts.snap
- packages/cli/__tests__/tasks/project-meta-task-test.ts
- packages/core/__tests__/__fixtures__/.checkuprc.json
- packages/core/__tests__/config-test.ts
- packages/core/src/config.ts
- packages/core/src/types/ember-template-lint.ts
- packages/core/src/types/parsers.ts
- yarn.lock
This PR is just a few cleanup tasks.
- upgrades dependencies to remove yarn warnings on install
- fixes lint issues related to the upgrades
- adds a test to ensure we can reach the config schema, and will error if that schema is moved or renamed (this happened, which is why I added this test)
> Fixes warnings, lint issues, and adds a test to ensure config schema is reachable

- packages/checkup-plugin-ember/__tests__/__snapshots__/ember-template-lint-summary-task-test.ts.snap
- packages/checkup-plugin-ember/__tests__/ember-template-lint-summary-task-test.ts
- packages/checkup-plugin-ember/src/actions/ember-template-lint-summary-actions.ts
- packages/checkup-plugin-ember/src/hooks/register-actions.ts
- packages/checkup-plugin-ember/src/hooks/register-tasks.ts
- packages/checkup-plugin-ember/src/tasks/ember-template-lint-summary-task.ts
- packages/cli/src/reporters/console-reporter.ts
This task is very similar to eslint-summary, but runs ember-template-lint instead of eslint. 
Sample output (running on travis-web) 
```
Template Lint Summary
Errors 252
■ require-button-type (70)
■ link-href-attributes (24)
■ no-invalid-interactive (33)
■ no-negated-condition (1)
■ no-triple-curlies (4)
■ no-quoteless-attributes (16)
■ simple-unless (5)
■ no-inline-styles (5)
■ require-valid-alt-text (57)
■ link-rel-noopener (35)
■ table-groups (1)
■ no-extra-mut-helper-argument (1)
```
> Adding task to run ember-template-lint

- .eslintrc
- package.json
- packages/checkup-plugin-javascript/__tests__/eslint-summary-task-test.ts
- packages/checkup-plugin-javascript/src/tasks/eslint-summary-task.ts
- packages/cli/__tests__/__snapshots__/task-list-test.ts.snap
- packages/cli/__tests__/commands/__snapshots__/run-test.ts.snap
- packages/cli/__tests__/commands/run-test.ts
- packages/cli/__tests__/task-list-test.ts
- packages/cli/src/commands/run.ts
- packages/cli/src/task-errors.ts
- packages/cli/src/task-list.ts
- packages/core/src/types/cli.ts
- packages/test-helpers/src/get-task-context.ts
- yarn.lock
This change expands the existing functionality of the command line options to include the ability to run tasks by either category or group.
Similar to the `task` option, you can now pass a `category` option (multiple times):
```shell
checkup --category 'best practices'
```
or a `group` option (multiple times)
```shell
checkup --group 'ember'
```
> Add ability to run tasks by category/group

- packages/test-helpers/src/checkup-fixturify-project.ts
Tests use to include a number of warnings during install. This fix removes that noise.
> Cleans up npm/yarn install output during tests

- checkup.code-workspace
- packages/checkup-plugin-javascript/__tests__/__snapshots__/outdated-dependencies-task-test.ts.snap
- packages/cli/__tests__/commands/__snapshots__/run-test.ts.snap
- packages/cli/__tests__/commands/run-test.ts
- packages/cli/src/commands/run.ts
- packages/cli/src/get-log.ts
- packages/cli/src/reporters/console-reporter.ts
The output should reflect only the tasks that were executed based on the passed flags.
Example: only executing the Octane migration task
```shell
❯ checkup --task=ember-octane/ember-octane-migration-status
Checkup report generated for travis v0.0.1 (1667 files analyzed)
This project is 9 years old, with 1446 active days, 5981 commits and 1661 files.
Checkup ran the following task(s) successfully:
✔ ember-octane-migration-status
Results have been saved to the following file:
/Users/scalvert/workspace/personal/travis-web/checkup-report-2020-12-14-13_55_57.sarif
checkup v0.12.0
config ba31c18af0bcc3546b98ae3e431b8a5f
Checking up on your project... done
```
Example: executing all configured tasks
```shell
❯ checkup
Checkup report generated for travis v0.0.1 (1668 files analyzed)
This project …
```
> Fixes output to only include tasks that were executed.

- packages/cli/README.md
- packages/cli/__tests__/commands/run-test.ts
- packages/cli/src/commands/run.ts
- packages/cli/src/reporters/json-reporter.ts
- packages/cli/src/tasks/project-meta-task.ts
- packages/core/src/types/cli.ts
- packages/test-helpers/src/get-task-context.ts
Checkup's existing flags used `camelCase` for flags with compound words. This feels less natural, as many CLIs use `kebab-case`. This change converts the existing compound words to kebab case.
```shell
❯ checkup --help
A health checkup for your project
USAGE
$ checkup [run] PATHS
ARGUMENTS
PATHS  The paths that checkup will operate on. If no paths are provided, checkup will run on the entire directory beginning
at --cwd.
OPTIONS
-c, --config=config                Use this configuration, overriding .checkuprc.* if present.
-d, --cwd=cwd                      The path referring to the root directory that Checkup will run in
-e, --exclude-paths=exclude-paths  Paths to exclude from checkup. If paths are provided via command line and via checkup
config, command line paths will be used.
-f, …
```
> Convert all flags to dasherized

- packages/checkup-plugin-ember-octane/src/tasks/ember-octane-migration-status-task.ts
- packages/core/__tests__/__fixtures__/simple.js
- packages/core/__tests__/parsers/ember-template-lint-parser-test.ts
- packages/core/__tests__/parsers/eslint-parser-test.ts
- packages/core/package.json
- packages/core/src/parsers/ember-template-lint-parser.ts
- packages/core/src/parsers/eslint-parser.ts
- packages/core/src/types/parsers.ts
Implements #828 
Allows for configuring tasks-based eslint/ember-template-lint configs via the config file's task configs.
Example:
```json
{
"$schema": "https://raw.githubusercontent.com/checkupjs/checkup/master/packages/core/src/schemas/config-schema.json",
"excludePaths": ["**/foo"],
"plugins": ["checkup-plugin-bar"],
"tasks": {
"bar/baz": ["on", {
"eslintConfig": {
//...
}
}],
"bar/booze": ["on", {
"emberTemplateLintConfig": {
//...
}
}]
}
}
```
> Extend lint tasks with custom config

- packages/checkup-plugin-ember-octane/src/tasks/ember-octane-migration-status-task.ts
- packages/checkup-plugin-ember/src/tasks/ember-dependencies-task.ts
- packages/checkup-plugin-ember/src/tasks/ember-in-repo-addons-engines-task.ts
- packages/checkup-plugin-ember/src/tasks/ember-template-lint-disable-task.ts
- packages/checkup-plugin-ember/src/tasks/ember-template-lint-summary-task.ts
- packages/checkup-plugin-ember/src/tasks/ember-test-types-task.ts
- packages/checkup-plugin-ember/src/tasks/ember-types-task.ts
- packages/checkup-plugin-javascript/src/tasks/eslint-disable-task.ts
- packages/checkup-plugin-javascript/src/tasks/eslint-summary-task.ts
- packages/checkup-plugin-javascript/src/tasks/outdated-dependencies-task.ts
- packages/cli/__tests__/__snapshots__/meta-task-list-test.ts.snap
- packages/cli/__tests__/__utils__/mock-meta-task-result.ts
- packages/cli/__tests__/commands/__snapshots__/run-test.ts.snap
- packages/cli/__tests__/commands/run-test.ts
- packages/cli/__tests__/generators/__snapshots__/generate-task-test.ts.snap
- packages/cli/__tests__/meta-task-list-test.ts
- packages/cli/__tests__/task-list-test.ts
- packages/cli/__tests__/tasks/project-meta-task-test.ts
- packages/cli/src/get-log.ts
- packages/cli/src/results/project-meta-task-result.ts
- packages/cli/src/types/index.ts
- packages/cli/templates/src/task/src/tasks/task.js.ejs
- packages/cli/templates/src/task/src/tasks/task.ts.ejs
- packages/core/src/base-task.ts
- packages/core/src/data/builders.ts
- packages/core/src/types/tasks.ts
Setting properties around what Task a Result is coming from in the builders directly, instead of doing it as a second step in `appendCheckupProperties`
> Removing `appendCheckupProperties` and doing it directly in the builders

- packages/checkup-plugin-ember/__tests__/__snapshots__/ember-dependencies-task-test.ts.snap
- packages/cli/__tests__/commands/__snapshots__/run-test.ts.snap
- packages/cli/__tests__/commands/run-test.ts
- packages/cli/src/reporters/verbose-console-reporter.ts
- packages/core/src/data/builders.ts
- packages/core/src/index.ts
- packages/core/src/utils/ui.ts
Right now, when a task doesnt find any data for results, it creates sort of an empty Result with the message 'No results found' for a given task. This was a hack put in when we realized that Results couldn't have an occurrenceCount of 0. This doesnt really align with the principle of what SARIF spec wants - its basically just creating a Result with occurrenceCount = 0 without setting occurrenceCount... more confusing than bug in the first place.
This change removes that hack, and only returns actual/meaningful Results. In the verbose-console-reporter, added function that renders a list of the tasks without results found, so it will be clearer for humans consuming this data.
Now, tasks without Results will render like this: 
```
No Results Found For
■ Ember In-Repo Addons / Engines
■ …
```
>     Removing empty Results from Result[]

- packages/checkup-plugin-ember-octane/__tests__/tasks/__snapshots__/ember-octane-migration-status-task-test.ts.snap
- packages/checkup-plugin-ember-octane/src/tasks/ember-octane-migration-status-task.ts
- packages/core/src/data/builders.ts
The messages we receive in the SARIF log come directly from the eslint/ember-template-lint task outputs. While these are OK, they don't make as much sense in the context of Checkup, in that Check's goal is to aggregate activities and help direct them.
To help alleviate this, I've updated the Octane task such that we provide more Checkup specific messages, which are in the format of:
```
Octane | <FEATURE> : <FEATURE MESSAGE>. More info: <INFO URL>
```
This results in the following in the SARIF viewer:
And when clicking through to the issue in the file:
> Updates Octane migration task with better messages

- packages/cli/__tests__/commands/__snapshots__/run-test.ts.snap
- packages/cli/src/reporters/verbose-console-reporter.ts
- packages/core/src/data/builders.ts
When you run eslint parser on files that `eslint-disable` rules that are not defined  in the parser, it throws an error
An example would be error: `Definition for rule 'ember-best-practices/no-side-effect-cp' was not found.` being added from a file that has `/* eslint-enable ember-best-practices/no-side-effect-cp */`, when `ember-best-practices` rules are not being run in the Task
Filtered thought out of Results and added a `Total:` count in the default verbose console output
> Filtering out eslint results that indicate a rule was not found

- packages/core/__tests__/utils/merge-lint-config-test.ts
- packages/core/src/parsers/ember-template-lint-parser.ts
- packages/core/src/parsers/eslint-parser.ts
- packages/core/src/utils/merge-lint-config.ts
The `deepmerge` package used to facilitate the deep merge of task configs overriding eslint or ember-template-lint configurations for a task was incorrectly merging tuple options. When it encountered two tuples, since they are arrays it would attempt to concat them, resulting in an incorrect structure.
Linting config:
```js
{
rules: {
'fake-eslint-rule': [
'warn',
{
prop1: 'error',
prop2: 'off',
},
],
},
}
```
Task config:
```js
{
rules: {
'fake-eslint-rule': [
'error',
{
prop1: 'warn',
prop2: 'off',
},
],
},
}
```
Merged configs:
```js
{
rules: {
'fake-eslint-rule': [
'warn',
{
prop1: 'error',
prop2: 'off',
},
'error',
{
prop1: 'warn',
prop2: 'off',
},
],
},
}
```
```js
{
rules: {
'fake-eslint-rule': [
'error',
{
prop1: 'warn',
prop2: 'off',
},
],
},
}
```
> Fixing task config overrides merging correctly

- checkup.code-workspace
- packages/checkup-plugin-ember/package.json
- packages/checkup-plugin-ember/src/hooks/register-task-reporters.ts
- packages/checkup-plugin-ember/src/reporters/ember-octane-migration-status-reporter.ts
- packages/checkup-plugin-ember/src/reporters/ember-template-lint-summary-reporter.ts
- packages/checkup-plugin-ember/src/reporters/ember-test-types-reporter.ts
- packages/checkup-plugin-javascript/package.json
- packages/checkup-plugin-javascript/src/hooks/register-task-reporters.ts
- packages/checkup-plugin-javascript/src/reporters/eslint-summary-reporter.ts
- packages/checkup-plugin-javascript/src/reporters/outdated-dependencies-reporter.ts
- packages/cli/src/reporters/verbose-console-reporter.ts
- packages/core/src/index.ts
- packages/core/src/utils/verbose-reporter-utils.ts
This is the first in a series of refactors to verbose-console-reporter. There will also be a change where some additional util functions (similar to `renderLintingSummaryResult`) exposed to offer an additional layer of options between using ui library and building result per task directly, and just using the current default behavior.
This change simply removes `output-map` and all task specific code from verbose-console-reporter, and moves it to the plugins directly. Our internal plugins should register custom reporters the same way we would expect an external plugin to. There are no functionality changes in this PR, just moving existing custom cases (where necessary) to plugins
> Removing `output-map` from verbose-console-reporter

- packages/cli/__tests__/generators/__snapshots__/generate-plugin-test.ts.snap
- packages/cli/src/generators/plugin.ts
- packages/cli/templates/src/plugin/package.json.js.ejs
This fixes an issue where the checkup versions are stale when stamping
out a new plugin leaving the developer with a completely broken setup.
> bugfix: Fix checkup versions in plugin

- packages/checkup-plugin-javascript/__tests__/__snapshots__/outdated-dependencies-task-test.ts.snap
- packages/core/package.json
- packages/core/src/parsers/ember-template-lint-parser.ts
- yarn.lock
This PR ensures that we pass `filePath` to `ember-template-lint` as part of the built in `ember-template-lint-parser`; we also drop `moduleId` since it was deprecated as part of https://github.com/ember-template-lint/ember-template-lint/pull/1760. This also updates `ember-template-lint` to latest.
> Include `filePath` as part of `ember-template-lint-parser`, update `ember-template-lint`

- packages/cli/src/generators/task.ts
When using the generator utils in tests, there was some excessively verbose output indicating that the `group` question didn't have an answer provided, mainly due to our defaults not including a default for that property. This PR adds defaults for both `category` and `group` questions.
> Fixes verbose output when using generator utils in tests

- packages/cli/__tests__/__utils__/fake-project.ts
- packages/cli/__tests__/cli-test.ts
- packages/test-helpers/src/checkup-fixturify-project.ts
Uses a symlink to the @checkup/core directory in the project during tests.
> Speeds up tests by using local link to @checkup/core in generated plugins

- packages/cli/src/index.ts
The last beta missed exporting the `CheckupTaskRunner` class, which is the core API that's expected to be used programmatically. This PR fixes that.
> Exporting task runner as public API

- packages/cli/__tests__/generators/__snapshots__/generate-plugin-test.ts.snap
- packages/cli/__tests__/generators/generate-plugin-test.ts
Previously, every time we published a new version, these snapshots would have to be updated. In reality, we don't care about the values of the different fields in the package.json, just the keys. Updated test to use matchers and only verify the keys
> Adding some abstractions to generate-plugin-test to reduce churn

- packages/cli/__tests__/__utils__/sarif-match-object.ts
- packages/cli/__tests__/checkup-task-runner-test.ts
- packages/cli/src/checkup.ts
- packages/cli/src/formatters/get-formatter.ts
- packages/cli/src/get-log.ts
- packages/core/src/types/checkup-result.ts
- packages/core/src/types/cli.ts
- packages/test-helpers/src/get-task-context.ts
As discussed, cleans up `RunOptions` to exclude `format`.
> Removes format from RunOptions to clean up Node API

- packages/cli/__tests__/checkup-task-runner-test.ts
- packages/cli/src/checkup.ts
- packages/cli/src/formatters/get-formatter.ts
- packages/core/src/types/cli.ts
- packages/test-helpers/src/get-task-context.ts
output-file only should be needed by the formatter, not the task runner. Also deleted some dead stuff
> Removing output-file from CheckupTaskRunner

- packages/cli/src/formatters/pretty.ts
Pretty formatter checked for outputFile !== '', but when outputFile was undefined, it didn't meet that condition, but should still be writing to console.
> Fixing bug in pretty formatter conditional

- packages/core/src/parsers/ember-template-lint-parser.ts
Changes the loop used in `ember-template-lint-parser` to use a `for..of` vs a `Promise.all`. This addresses issues where, for large applications, using a `Promise.all` was temporarily inflating memory and causing OOMs.
> Fixes loop in ember-template-lint-parser

- packages/core/src/errors/checkup-error.ts
- packages/core/src/errors/error-kind.ts
By typing the map based on the enum used in its keys you get better feedback when indexing it. This also helps the compiler understand the resulting value may be undefined and forces that condition to be handled instead of failing with something useless like"undefined is not a function".
An alternative would be to define ERROR_BY_KIND keys for the remaining ErrorKind values, in which case the resulting value would never be undefined.
> Improve type definition for error kind map

- packages/checkup-plugin-ember/src/formatters/ember-octane-migration-status-formatter.ts
- packages/checkup-plugin-ember/src/formatters/ember-template-lint-summary-formatter.ts
- packages/checkup-plugin-ember/src/formatters/ember-test-types-formatter.ts
- packages/checkup-plugin-javascript/src/formatters/eslint-summary-formatter.ts
- packages/checkup-plugin-javascript/src/formatters/outdated-dependencies-formatter.ts
- packages/cli/__tests__/__fixtures__/checkup-formatter-test/index.js
- packages/cli/__tests__/__fixtures__/checkup-formatter-test/package.json
- packages/cli/__tests__/__utils__/fake-project.ts
- packages/cli/__tests__/cli-test.ts
- packages/cli/jest.config.js
- packages/cli/src/formatters/formatter-utils.ts
- packages/cli/src/formatters/get-formatter.ts
- packages/cli/src/formatters/json.ts
- packages/cli/src/formatters/pretty.ts
- packages/cli/src/formatters/summary.ts
- packages/core/src/errors/error-kind.ts
- packages/core/src/types/cli.ts
- packages/core/src/types/tasks.ts
- packages/core/src/utils/pretty-formatter-utils.ts
- packages/test-helpers/src/checkup-fixturify-project.ts
Allows the ability to specify custom formatters.
Using a relative path:
```sh
checkup run . --format ./my-custom-formatter.js
```
Using an external module:
```sh
checkup run . --format checkup-formatter-custom
```
> Adds ability to specify custom formatters

- packages/cli/__tests__/checkup-task-runner-test.ts
- packages/cli/src/api/checkup-task-runner.ts
- packages/cli/src/checkup.ts
- packages/core/src/types/cli.ts
Giving paths a default value in RunOptions, used by CheckupTaskRunner
> Making paths an optional param in RunOptions, defaulting to `.`

- packages/cli/__tests__/checkup-task-runner-test.ts
- packages/cli/__tests__/cli-test.ts
- packages/cli/src/api/checkup-task-runner.ts
- packages/cli/src/checkup.ts
- packages/core/src/config.ts
- packages/core/src/types/cli.ts
Renamed `config` param to `config-path`; `config` param now accepts an inline config.
> Adding support to pass in a config inline to checkup

- packages/cli/src/api/checkup-task-runner.ts
- packages/core/__tests__/config-test.ts
- packages/core/src/config.ts
- packages/core/src/index.ts
There was a bug introduced in the previous change to support inline configs that broke checkup finding a config at root/.checkuprc by default. This fixes that, and cleans up some of the naming to be more straightforward
> Fixing bug in config code

- packages/cli/__tests__/cli-test.ts
- packages/cli/src/api/checkup-task-runner.ts
- packages/cli/src/checkup.ts
- packages/core/src/types/cli.ts
We currently use the cwd prop used as "where do i look for the code to run checkup on" and "where should checkup look for the source code for the plugins". 
This PR adds in a new option to specify a directory for the latter, which is useful for running checkup via node api in a script run in the context of other repos.
> Adding option to specify a pluginBaseDir directory

- packages/checkup-plugin-ember/package.json
- packages/checkup-plugin-ember/src/tasks/ember-dependencies-task.ts
- packages/cli/src/api/checkup-task-runner.ts
- packages/cli/src/utils/get-package-json.ts
- packages/core/package.json
- packages/core/src/ast/ast-transformer.ts
- packages/core/src/ast/babel-traverser.ts
- packages/core/src/ast/json-traverser.ts
- packages/core/src/ast/typescript-traverser.ts
- packages/core/src/index.ts
- packages/core/src/types/tasks.ts
- packages/test-helpers/src/get-task-context.ts
- tsconfig-base.json
- yarn.lock
This PR looks to accomplish a number of things:
1. Updates the `ember-dependencies` task to return a single result per dependency rather than a single result with a `data` property in the `properties` bag
2. Updates the `ember-dependencies` task to include source information, specifically line and column data
3. Adds a number of AST classes (more information to follow)
Following PRs will do the following:
1. Align the `javascript/outdated-dependencies` task to use this same source information for individual dependencies
2. Update the `ember-dependencies` task to include version information to align it with the outdated dependencies (ideally both tasks will pull data from the same source - the ember task will filter on ember info, and the outdated deps will filter only those dependencies …
> Part 1: Ensure results adhere to SARIF specifications

- packages/checkup-plugin-ember/src/tasks/ember-dependencies-task.ts
- packages/checkup-plugin-javascript/__tests__/outdated-dependencies-task-test.ts
- packages/checkup-plugin-javascript/src/actions/outdated-dependency-actions.ts
- packages/checkup-plugin-javascript/src/tasks/outdated-dependencies-task.ts
- yarn.lock
Converts `outdated-dependencies` task to more standardized SARIF format. Additionally includes source information for SARIF log.
> Part 2: Ensure results adhere to SARIF specifications

- packages/cli/__tests__/__utils__/fake-project.ts
- packages/cli/__tests__/cli-test.ts
- packages/cli/src/api/checkup-task-runner.ts
Previously it was possible to load plugins from another directory that contained a `node_modules` directory. This would not allow you to load plugins from an arbitrary nested directory that didn't contain a `node_modules`. This change widens this functionality to allow for this use case.
> Allows for loading plugins from arbitrary directories using `--plugin-base-dir`

- tsconfig-base.json
Building a fresh master resulted in a number of TS compilation errors.
```shell
$ yarn build
yarn run v1.22.4
$ tsc --build
node_modules/@types/eslint/helpers.d.ts:1:6 - error TS2300: Duplicate identifier 'Prepend'.
1 type Prepend<Tuple extends any[], Addend> = ((_: Addend, ..._1: Tuple) => any) extends ((
~~~~~~~
../node_modules/@types/eslint/helpers.d.ts:1:6
1 type Prepend<Tuple extends any[], Addend> = ((_: Addend, ..._1: Tuple) => any) extends (..._: infer Result) => any
~~~~~~~
'Prepend' was also declared here.
../node_modules/@types/eslint/helpers.d.ts:1:6 - error TS2300: Duplicate identifier 'Prepend'.
1 type Prepend<Tuple extends any[], Addend> = ((_: Addend, ..._1: Tuple) => any) extends (..._: infer Result) => any
~~~~~~~
node_modules/@types/eslint/helpers.d.ts:1:6
1 type …
```
> Resolves type errors when building fresh master

- packages/cli/__tests__/cli-test.ts
- packages/cli/__tests__/generators/__snapshots__/generate-task-test.ts.snap
- packages/cli/templates/src/task/src/tasks/task.js.ejs
- packages/cli/templates/src/task/src/tasks/task.ts.ejs
The generators for tasks was not updated since the new `addResult` API was introduced. This PR updates both the .js and .ts templates to output the correct structure.
> Fixes task generator to output correct new Task format

- packages/checkup-plugin-ember/__tests__/__snapshots__/ember-octane-migration-status-task-test.ts.snap
- packages/checkup-plugin-ember/src/tasks/ember-octane-migration-status-task.ts
- packages/cli/src/checkup.ts
- packages/cli/src/formatters/json.ts
- packages/cli/src/formatters/summary.ts
- packages/core/src/data/lint.ts
- packages/core/src/types/cli.ts
This is the second part of #1049, and changes the other two formatters to return strings.
Of note, the summary formatter still uses the `outputFile` option, mainly as its output isn't meant to be stored in a file. If we feel this is confusing or inconsistent, we can change it.
Note: This PR also includes some fixes to the Octane migration status task that were found during testing.
> Change other formatters to return strings

- packages/core/src/analyzers/handlebars-analyzer.ts
- packages/core/src/analyzers/javascript-analyzer.ts
- packages/core/src/analyzers/typescript-analyzer.ts
When auto-generating the documentation for `checkupjs.github.io`, the syntax fixed in this PR was causing errors to be thrown when converting from jsdoc to markdown. This PR removes the invalid syntax.
> Fixes invalid syntax for type output

- packages/checkup-plugin-javascript/__tests__/lines-of-code-task-test.ts
- packages/checkup-plugin-javascript/src/tasks/lines-of-code-task.ts
In the lines of code test, the cwd was not being trimmed properly, leading to filepaths like /foo.js as opposed to foo.js. This doesnt match the patterns of the other tasks, causing scripts that consume these results to not normalize them correctly
> [bugfix] Fixing URI in LOC task

- packages/checkup-plugin-javascript/docs/tasks/lines-of-code-task.md
- packages/cli/__tests__/generators/__snapshots__/generate-actions-test.ts.snap
- packages/cli/templates/src/actions/src/actions/actions.js.ejs
The actions generator for JS was outputting es6 module syntax, which would require the plugins to have a transpile step (which they don't have). This fix ensures they're inline with other JS output for generated code (plugins, tasks).
> Fixes actions generator for JavaScript

- packages/cli/src/checkup.ts
- packages/cli/src/formatters/file-writer.ts
- packages/cli/src/formatters/json.ts
- packages/cli/src/formatters/summary.ts
- packages/cli/src/index.ts
- packages/core/src/types/cli.ts
This exports the writeResultFile from cli, and adds writeResultsToFile as an optional function on the Formatter interface, to expose it for formatters that populate it
> Add export to @checkup/cli for writeResultFile

- packages/cli/bin/checkup.js
- packages/cli/package.json
- yarn.lock
If checkup is invoked as a global, we want to ensure that it's first using a locally installed version, and falls back to using a global if present.
eg.
**Invoking checkup when checkup is installed locally:**
```sh-session
checkup run .
```
Should use the **local** version of `@checkup/cli`. 
**Invoking checkup globally when checkup is installed locally:**
```sh-session
checkup run .
```
Should use the **local** version of `@checkup/cli`. 
**Invoking checkup globally when checkup is _not_ installed locally:**
Either via `npx`:
```sh-session
npx @checkup/cli run .
```
Or via global install:
```sh-session
checkup run .
```
Should use the **global** version of `@checkup/cli`.
> Ensuring global execution defaults to local if present

- packages/checkup-plugin-ember/src/tasks/ember-dependencies-task.ts
- packages/checkup-plugin-ember/src/tasks/ember-in-repo-addons-engines-task.ts
- packages/checkup-plugin-ember/src/tasks/ember-octane-migration-status-task.ts
- packages/checkup-plugin-ember/src/tasks/ember-template-lint-disable-task.ts
- packages/checkup-plugin-ember/src/tasks/ember-template-lint-summary-task.ts
- packages/checkup-plugin-ember/src/tasks/ember-test-types-task.ts
- packages/checkup-plugin-ember/src/tasks/ember-types-task.ts
- packages/checkup-plugin-javascript/src/tasks/eslint-disable-task.ts
- packages/checkup-plugin-javascript/src/tasks/eslint-summary-task.ts
- packages/checkup-plugin-javascript/src/tasks/lines-of-code-task.ts
- packages/checkup-plugin-javascript/src/tasks/outdated-dependencies-task.ts
- packages/cli/__tests__/cli-test.ts
- packages/cli/__tests__/generators/__snapshots__/generate-task-test.ts.snap
- packages/cli/src/api/checkup-task-runner.ts
- packages/cli/src/formatters/summary.ts
- packages/cli/templates/src/task/src/tasks/task.js.ejs
- packages/cli/templates/src/task/src/tasks/task.ts.ejs
- packages/core/__tests__/base-task-test.ts
- packages/core/__tests__/data/checkup-log-builder-test.ts
- packages/core/src/base-task.ts
- packages/core/src/data/checkup-log-builder.ts
- packages/core/src/data/checkup-log-parser.ts
- packages/core/src/data/sarif-log-builder.ts
- packages/core/src/types/checkup-log.ts
- packages/core/src/types/tasks.ts
- packages/test-helpers/src/get-task-context.ts
The `addResult` API is a cleaner addition to the `Task` class, and helps for adding valid SARIF to the resulting log. One awkward part of that API was it being overloaded to _also_ add the rule metadata. The awkwardness centered around a few things:
- it felt like a side-effect to invoke `addRule` inside `addResult`
- if no results were found for a task, the rule metadata would never be populated
- calling `addResult` multiple times, which is pretty common, would result in `addRule` being also called multiple times unnecessarily. While there was logic in `addRule` to ensure a new rule wasn't added every time it was called if one already existed, this still felt like unnecessary execution
- it made it hard for users to understand the relationship between the rule metadata and a result. …
> Extracting rule metadata from addResult

- packages/checkup-plugin-ember/src/tasks/ember-octane-migration-status-task.ts
- packages/core/src/data/lint.ts
- packages/core/src/types/tasks.ts
Any errors that are generated from using the lint analyzers can cause subsequent data loss due to invalid filtering of those errors. This was evident in the octane migration task, where parsing errors or global errors caused this data loss to manifest.
It's important to understand why those errors are occuring in the first place, but our code should be resilient to them propagating into the SARIF logs. This PR resolves this issue.
> Fixes errors in lint results causing incorrect data

- packages/checkup-formatter-pretty/__tests__/pretty-test.tsx
- packages/checkup-formatter-pretty/src/pretty-formatter.tsx
Due to changes to the way we build rule metadata, there are now differences in the way we want to output results. 
Formerly the pretty formatter would try to indicate when no results were present, which helped verify to the user that the task ran with no results. Since the change to _always_ allow rule metadata, and the addition of tracking executed tasks separately, we needed to additionally filter when outputting the 'no results' info to only do so for executed tasks.
> Fixes Pretty formatter outputing empty results for all tasks

- packages/core/__tests__/utils/get-paths-test.ts
- packages/core/src/utils/get-paths.ts
There was a bug in the get-paths module where it was incorrectly truncating the paths for directories (`/somedir`). Specifically, that directory would explicitly be removed from the full path, resulting in an invalid path on disc.
> Fixes bug in get-paths where subdir segments were truncated

- packages/checkup-formatter-pretty/__tests__/components/bar-test.tsx
- packages/checkup-formatter-pretty/__tests__/components/list-test.tsx
- packages/checkup-formatter-pretty/__tests__/components/migration-test.tsx
- packages/checkup-formatter-pretty/__tests__/components/table-test.tsx
- packages/checkup-formatter-pretty/__tests__/components/validation-test.tsx
- packages/checkup-formatter-pretty/package.json
- packages/checkup-formatter-pretty/src/components/validation.tsx
- packages/core/__tests__/base-validation-task-test.ts
- packages/core/src/base-migration-task.ts
- packages/core/src/base-task.ts
- packages/core/src/base-validation-task.ts
- packages/core/src/index.ts
This PR supersedes #855, which started the implementation of the validation task base class, but stalled due to its coupling with the addition of a validate command (which was decided against).
This adds the following:
1. A new `BaseValidationTask` class with associated APIs that make it easy to add validation-based tasks
2. A new `validation` component in the pretty formatter to output the validation steps.
The APIs allow you to add a validation step, which is defined using the following signature:
```ts
type ValidationResult = {
isValid: boolean;
options?: TaskResultOptions;
};
addValidationStep(messageText: string, validate: () => ValidationResult);
```
A `validate` function consists of a function that returns whether the computation performed within it was valid or not. It's also …
> Adds validation task base class and associated component

- packages/core/src/base-task.ts
The syntax currently used for the jsdoc comment causes a syntax error when used via mdx rendering.
> Fixes base-task jsdoc generating invalid syntax for docs (mdx)

- packages/checkup-plugin-ember/__tests__/__snapshots__/ember-octane-migration-status-task-test.ts.snap
- packages/core/package.json
- yarn.lock
This upgrade includes an expansion of AST node location support, specifically adding `endLine` and `endColumn`. This allows the SARIF logs to include more accurate AST info for physical locations of artifacts.
> Upgrades ember-template-lint to 3.11.0

- packages/checkup-plugin-javascript/__tests__/valid-esm-package-task-test.ts
- packages/checkup-plugin-javascript/package.json
- packages/checkup-plugin-javascript/src/index.ts
- packages/checkup-plugin-javascript/src/tasks/valid-esm-package-task.ts
- packages/core/__tests__/base-validation-task-test.ts
- packages/core/src/base-validation-task.ts
- yarn.lock
Adds a new validation task for validating ESM packages.
Validation output:
```sh-session
Checkup ran the following task(s) successfully:
Valid ESM Package
=================
Validation passed
✔ Contains "type" property set to "module" in package.json
✔ Does not contain a "main" property in package.json
✔ Contains an "exports" property set to a valid value in package.json
✔ Requires at least Node 13.2.0 in the "engines" property of package.json
✔ Should not have "use strict" in any JavaScript files
```
Uses heuristic from https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c to determine if a package is a valid ESM package.
> Adds valid-esm-package-task

- packages/checkup-plugin-javascript/__tests__/eslint-disable-task-test.ts
- packages/checkup-plugin-javascript/src/tasks/eslint-disable-task.ts
- packages/cli/__tests__/task-list-test.ts
- packages/cli/src/task-list.ts
- packages/core/src/analyzers/ast-analyzer.ts
- packages/core/src/base-task.ts
- packages/core/src/types/tasks.ts
Previously, when a single file could not be parsed correctly, the entire eslint-disable task would fail. We want to notify our consumers when a file can not be parsed, or when any error occurs when analyzing a single file, but we dont necessarily want that to cause the whole task to fail. It is now up to the author of a task whether they just want to throw an error when a failure is caught, or just add a nonFatalError, which are all collected at the end and pushed to the `toolExecutionNotifications`.
Added new public function `addNonFatalError` to base-task, and collected the nonFatalErrors in task-list with the other (fatal) errors. This approach pushes the responsibility of handling failures in the analyzers onto the task authors, giving them full control of how they want to handle what …
> [enhancement] Adding non-fatal errors to tasks

- packages/core/src/data/checkup-log-builder.ts
this fixes #1142 
without fix (running task with v 1.0.1 of @checkup/core): 
```
➜  checkup run . --task a11y-violations-summary
yarn run v1.22.4
$ checkup run . --task a11y-violations-summary
Error Cannot read property 'message' of undefined
✨  Done in 6.54s.
``` 
with fix (running task with v 1.0.1 of @checkup/core): 
```
➜  checkup run . --task a11y-violations-summary
yarn run v1.22.4
$ checkup run . --task a11y-violations-summary
Checkup report generated for sample v0.0.0-productSpec (5925 files analyzed)
This project is 3 years, 4 months old, with 774 active days, 4073 commits and 5915 files.
Checkup ran the following task(s) successfully:
✔ a11y-violations-summary
Results have been saved to the following file:
/Users/jsmith/project/checkup-report-2021-11-29-13_32_54.sarif
checkup …
```
> backwards incompatibility issue introduced in 1.4.0

- packages/core/src/analyzers/dependency-analyzer.ts
From `npm-check` docs:
> #### `-s, --skip-unused`
>
> By default `npm-check` will let you know if any of your modules are not being used by looking at `require` statements in your code.
>
> This option will skip that check. 
Checkup doesn't use this info when calculating out-of-date dependencies, and it causes a big spike in open files due to how `depcheck` works internally.
This PR is a small change to avoid that.
> Skip unused dependency check to avoid depcheck open file spike

- .github/workflows/auto-merge.yml
- packages/checkup-plugin-javascript/__tests__/outdated-dependencies-task-test.ts
This PR adds dependabot [auto-merge](https://github.com/marketplace/actions/dependabot-auto-merge) to the repository.
Please ensure you have creacted a GitHub token called `AUTO_MERGE` as per the instructions [here](https://github.com/marketplace/actions/dependabot-auto-merge#token-scope).
---
*This change was executed automatically with [Shepherd](https://github.com/NerdWalletOSS/shepherd).* 💚🤖
> Adds dependabot auto-merge configuration

- packages/checkup-formatter-pretty/jest.config.js
- packages/checkup-plugin-ember/__tests__/__snapshots__/ember-octane-migration-status-task-test.ts.snap
- packages/checkup-plugin-ember/__tests__/ember-template-lint-disable-task-test.ts
- packages/checkup-plugin-ember/__tests__/ember-template-lint-summary-task-test.ts
- packages/checkup-plugin-ember/__tests__/ember-test-types-task-test.ts
- packages/checkup-plugin-ember/jest.config.js
- packages/checkup-plugin-javascript/__tests__/eslint-disable-task-test.ts
- packages/checkup-plugin-javascript/__tests__/eslint-summary-task-test.ts
- packages/checkup-plugin-javascript/__tests__/lines-of-code-task-test.ts
- packages/checkup-plugin-javascript/__tests__/outdated-dependencies-task-test.ts
- packages/checkup-plugin-javascript/jest.config.js
- packages/cli/__tests__/generators/__snapshots__/generate-plugin-test.ts.snap
- packages/cli/__tests__/task-list-test.ts
- packages/cli/__tests__/task-result-comparator-test.ts
- packages/cli/jest.config.js
- packages/core/__tests__/analyzers/ember-template-lint-analyzer-test.ts
- packages/core/__tests__/analyzers/eslint-analyzer-test.ts
- packages/core/__tests__/base-task-test.ts
- packages/core/__tests__/base-validation-task-test.ts
- packages/core/__tests__/config-test.ts
- packages/core/__tests__/data/checkup-log-builder-test.ts
- packages/core/__tests__/data/checkup-log-parser-test.ts
- packages/core/__tests__/data/sarif-log-builder-test.ts
- packages/core/__tests__/utils/__snapshots__/calculate-section-bar-test.ts.snap
- packages/core/__tests__/utils/calculate-section-bar-test.ts
- packages/core/__tests__/utils/file-paths-array-test.ts
- packages/core/__tests__/utils/merge-lint-config-test.ts
- packages/core/jest.config.js
- packages/plugin/jest.config.js
Using the jest setting `snapshotFormat.printBasicPrototype = false` produces more readable, copyable snapshots. This change sets all configs to use this setting, and regenerates all snapshots.
> Update jest to use printBasicPrototype for snapshotFormat

- packages/cli/src/checkup.ts
- packages/cli/src/commands/generate.ts
- packages/cli/src/commands/generate/actions.ts
- packages/cli/src/commands/generate/config.ts
- packages/cli/src/commands/generate/plugin.ts
- packages/cli/src/commands/generate/task.ts
- packages/cli/src/commands/run.ts
The current structure of yargs commands within the `checkup.ts` module are hard to maintain due to their size and complexity. Since yargs supports external modules for individual commands, this PR splits that existing module into a number of smaller modules:
```bash
├── checkup.ts
├── commands
│   ├── generate
│   │   ├── actions.ts
│   │   ├── config.ts
│   │   ├── plugin.ts
│   │   └── task.ts
│   ├── generate.ts
│   └── run.ts
```
The two top-level commands are contained within the top level of the `commands` directory. Sub-commands of generate are contained under a `generate` directory.
> Extract commands into separate modules

- packages/checkup-plugin-javascript/package.json
Fixes issue in `checkup-plugin-javascript` where `babel-eslint` was set as a parser in a task config, but wasn't present.
> Adding missing package required by tasks using eslint configurations

- packages/checkup-plugin-ember/src/tasks/ember-octane-migration-status-task.ts
- packages/checkup-plugin-ember/src/tasks/ember-test-types-task.ts
- packages/checkup-plugin-javascript/__tests__/eslint-summary-task-test.ts
- packages/checkup-plugin-javascript/src/tasks/eslint-summary-task.ts
- packages/checkup-plugin-javascript/src/tasks/valid-esm-package-task.ts
- packages/core/__tests__/analyzers/eslint-analyzer-test.ts
- packages/core/__tests__/utils/merge-lint-config-test.ts
- packages/core/src/analyzers/eslint-analyzer.ts
- packages/core/src/types/analyzers.ts
- packages/core/src/utils/merge-lint-config.ts
The `CLIEngine` class was deprecated in `ESLint`, and removed in v8. In order to support upgrading to the latest ESLint, and to enable full conversion to ESM, this PR first updates the API. Subsequent PRs will upgrade to ESLint 8.
Breaking because the `ESLintAnalyzer`'s `engine` property is public, and the methods on that object have changed.
Details: https://eslint.org/docs/8.0.0/user-guide/migrating-to-8.0.0#-the-cliengine-class-has-been-removed
> Converts to using ESLint class vs deprecated CLIEngine

- package.json
- packages/checkup-plugin-ember/package.json
- packages/checkup-plugin-ember/src/tasks/ember-octane-migration-status-task.ts
- packages/checkup-plugin-javascript/package.json
- packages/core/__tests__/analyzers/ember-template-lint-analyzer-test.ts
- packages/core/package.json
- packages/core/src/analyzers/ember-template-lint-analyzer.ts
- yarn.lock
Replaces #1176
Upgrading `ember-template-lint` constitutes a breaking change due to its effect on the associated analyzer (invocations may produce different results due to rules changing).
> Upgrades ember-template-lint to 4.8.0

- packages/cli/__tests__/cli-test.ts
- packages/core/src/data/checkup-log-builder.ts
The current output listing executed tasks used the `taskName`, not the `fullyQualifiedTaskName`. This created inconsistency between names when outputting tasks in different ways. For example, when using `--list-tasks`, we'd use the `fullyQualifiedTaskName`, but when outputting tasks that were run in the `summary` formatter, we were using the short `taskName`, which didn't include the task's plugin namespace. This PR fixes this so that all output is consistent.
> Update executed tasks to use fully qualified task name

- packages/cli/__tests__/cli-test.ts
- packages/cli/src/generators/config.ts
- packages/core/__tests__/utils/get-paths-test.ts
- packages/core/src/utils/get-paths.ts
Updates file path expansion logic to simplify and correctly observe path exclusions. Fixes a long standing bug with Checkup incorrectly including `dot` paths/directories.
> Refactors path expansion for CLI inputs

- packages/core/src/utils/get-paths.ts
Certain repositories use things such as yarn workspaces, which nest addons in packages. Those build folders would not be ignored before. This fixes that.
> Recursively ignore build files

- packages/core/tests/config-test.ts
- packages/test-helpers/package.json
- yarn.lock
Fixes a deprecated path from the test refactor (#1249) and adding missing dependency in `@checkup/test-helpers`.
> Minor fixes to paths in test, adding missing dependency

- packages/ui/package.json
- packages/ui/src/base-ui-formatter.ts
- yarn.lock
The implementation of `ink-render-string` was incorrect within this repo. This was partly due to the fact that that repo wasn't being published correctly - it was publishing `.ts` files rather than transpiled `.js` files. [This PR fixed that issue](https://github.com/zhanwang626/ink-render-string/pull/4), and this PR is a follow up to address its usage within Checkup.
> Fixes invalid usage of ink-render-string

- packages/core/src/analyzers/typescript-analyzer.ts
Fixes import for `@babel/traverse` to use `default` import.
> Fixes @babel/traverse import

- packages/test-helpers/src/checkup-fixturify-project.ts
Fixes issue with destructuring CJS module in ESM.
```
SyntaxError: Named export 'symlinkSync' not found. The requested module 'fs-extra' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
import pkg from 'fs-extra';
const { symlinkSync, mkdirpSync } = pkg;
```
> Fixes destructure of fs-extra

- package.json
- packages/checkup-plugin-ember/tests/__snapshots__/ember-octane-migration-status-task-test.ts.snap
- packages/checkup-plugin-javascript/tests/lines-of-code-task-test.ts
- packages/cli/bin/checkup.js
- packages/cli/src/formatters/components/Pretty.tsx
- packages/core/src/base-task.ts
- packages/core/tests/base-task-test.ts
- packages/core/tests/base-validation-task-test.ts
- packages/ui/src/base-ui-formatter.ts
- packages/ui/src/components/List.tsx
- packages/ui/src/components/Table.tsx
- packages/ui/tests/components/list-test.tsx
- packages/ui/tests/components/migration-test.tsx
- yarn.lock
There's a current mismatch of the tasknames that are stored in the rules meta vs. the tasks themselves, in that the rules meta stores the fully qualified task name, and the tasks themselves to not. This PR fixes this inconsistency.
> Uses fully qualified task name everywhere

- packages/cli/package.json
- packages/cli/src/formatters/get-formatter.ts
- packages/cli/src/formatters/stylish.ts
- packages/cli/tests/__fixtures__/checkup-result-short.sarif
- packages/cli/tests/formatters/stylish-test.ts
- packages/core/package.json
- packages/core/src/data/checkup-log-parser.ts
- packages/core/src/types/tasks.ts
- yarn.lock
We've spent a lot of time with the Pretty formatter, in multiple incarnations. The latest, which leverages the excellent Ink library, provides some pretty robust functionality, but sadly has also resulted in a lot of maintenance burden. The amount of benefit it gives is outweighed by the additional maintenance cost, all for a formatter.
As such, we're deprecating the pretty formatter and its associated infra (`@checkup/ui` package). This will be done in a follow up PR.
To replace it, we're outputting the SARIF in a familiar format used by other static analysis tools, such as `eslint` and `ember-template-lint`. 
New `stylish` formatter:
This formatter has a number of improvements over the pretty formatter:
1. It works with SARIF, and is very fault-tolerant
2. It outputs both location …
> Adding stylish formatter to replace pretty formatter (deprecated)

- packages/cli/bin/checkup.js
- packages/cli/package.json
- packages/cli/src/api/generator.ts
- packages/cli/src/generators/base-generator.ts
- packages/core/src/config.ts
- yarn.lock
There were 2 imports that were using the `import * as ...` syntax, which caused errors on the imports in ESM. This fixes those, in addition to removing `v8-compile-cache`, which doesn't work with ESM.
> Fixes segfault in generators

- packages/checkup-plugin-ember/package.json
- packages/checkup-plugin-ember/tests/ember-template-lint-disable-task-test.ts
- packages/checkup-plugin-javascript/package.json
- packages/core/package.json
- yarn.lock
This change updates ember-template-recast to 6.1.3 to support newer glimmer syntax.
See: https://deprecations.emberjs.com/v3.x/#toc_argument-less-helper-paren-less-invocation
> [dep] Upgrade ember-template-recast to 6.1.3 to support new glimmer syntax

- packages/checkup-plugin-javascript/src/tasks/eslint-disable-task.ts
- Fixes https://github.com/checkupjs/checkup/issues/1347 which has more info
- gjs/gts files requires using the `eslint-plugin-ember` eslint plugin to do the preprocessing for `<template>` tags
- The task `eslint-summary-task` uses the `eslintrc` file so it works as expected
> Remove gts/gjs from eslint-disable-task glob since babel parser does not support it

- packages/checkup-plugin-javascript/src/tasks/eslint-summary-task.ts
Avoid running checkup on autogenerated files
> Update eslint-summary-task to disregard *.d.ts files

- packages/checkup-plugin-ember/src/tasks/ember-octane-migration-status-task.ts
- packages/checkup-plugin-ember/src/tasks/ember-template-lint-summary-task.ts
Avoid running checkup on autogenerated files
> Update ember-template-lint-summary-task and ember-octane-migration-status-task to disregard *.d.ts files

- packages/checkup-plugin-javascript/src/tasks/eslint-disable-task.ts
- Avoid running checkup on autogenerated files
- Fix parsing issue when given a typescript file by using the typescript parser
Example error:
```
{"message":{"text":"javascript/eslint-disables generated an error during execution"},"level":"error","associatedRule":{"id":"javascript/eslint-disables"},"exception":{"message":"Error occurred at file.ts. Unexpected token, expected \",\" (24:29)"
```
> Update eslint-disable-task to disregard *.d.ts files and use recast typescript parser
