checkupjs/checkup

SPEC.md

[Rendered](https://github.com/checkupjs/checkup/blob/spec/SPEC.md)

Adding Checkup spec

---

checkup.code-workspace

Adding a vs-code workspace so that we can suggest plugins and expand to default settings/folders in the future.

Add a vs-code workspace

---

packages/cli/README.md
packages/cli/__tests__/__snapshots__/index-test.ts.snap
packages/cli/__tests__/index-test.ts
packages/cli/jest.config.js
packages/cli/package.json
packages/cli/src/index.ts
packages/core/package.json
packages/core/src/index.ts
packages/core/src/loaders/plugin-loader.ts
packages/core/src/types/index.ts
packages/core/src/utils/get-config.ts
packages/plugin-ember/package.json
packages/test-helpers/package.json
packages/test-helpers/src/checkup-fixturify-project.ts
packages/test-helpers/src/index.ts
packages/test-helpers/src/plugin.ts
packages/test-helpers/tsconfig.json
tsconfig.json
yarn.lock

Add support for dynamically loading plugins specified in the consumer
checkup config plugins field.

feat(core): Add Support for Plugins via Config File

---

SPEC.md

Adding in use cases and persona information to the spec

Adding use cases and personas into the spec

---

packages/plugin-ember-octane/__tests__/__fixtures__/sample-octane-eslint-report.json
packages/plugin-ember-octane/__tests__/results/__snapshots__/octane-migration-status-tast-result-test.ts.snap
packages/plugin-ember-octane/__tests__/results/octane-migration-status-tast-result-test.ts
packages/plugin-ember-octane/src/results/octane-migration-status-task-result.ts

Changes:
- Output ESLint completion info to JSON for plugin-ember-octane.
Related: #68

feat(plugin-ember-octane): Output completion info to JSON

---

packages/cli/__tests__/__utils__/mock-task-result.ts
packages/cli/__tests__/index-test.ts
packages/core/src/types/index.ts
packages/plugin-default/src/results/project-info-task-result.ts
packages/plugin-ember-octane/src/results/octane-migration-status-task-result.ts
packages/plugin-ember/src/results/dependencies-task-result.ts
packages/plugin-ember/src/results/ember-project-task-result.ts
packages/plugin-ember/src/results/types-task-result.ts

Working on PR that adds PDF function to all results to format as pdf. This eventually wont be void, but to minimize changes in subsequent PR, adding void function to each result

Adding PDF function to task results

---

packages/plugin-ember-octane/__tests__/results/__snapshots__/octane-migration-status-tast-result-test.ts.snap
packages/plugin-ember-octane/__tests__/results/octane-migration-status-tast-result-test.ts
packages/plugin-ember-octane/src/results/octane-migration-status-task-result.ts

ESLint console output

---

packages/cli/__tests__/__snapshots__/pdf-test.ts.snap
packages/cli/__tests__/__utils__/mock-task-result.ts
packages/cli/__tests__/index-test.ts
packages/cli/__tests__/pdf-test.ts
packages/cli/src/commands/run.ts
packages/cli/src/helpers/pdf.ts
packages/cli/src/static/components/card.hbs
packages/cli/src/static/report-template.hbs
packages/core/src/index.ts
packages/core/src/pdf-components/card-data.ts
packages/core/src/pdf-components/pdf-component-data.ts
packages/core/src/types/index.ts
packages/plugin-default/src/results/project-info-task-result.ts
packages/plugin-ember-octane/src/results/octane-migration-status-task-result.ts
packages/plugin-ember/src/results/dependencies-task-result.ts
packages/plugin-ember/src/results/ember-project-task-result.ts
packages/plugin-ember/src/results/types-task-result.ts
tsconfig.json

This adds in a partial to render a card component in the report, and modifies some existing infrastructure to allow for pdf data to be generated.

Add in card partial scaffolding

---

packages/cli/__tests__/generators/__snapshots__/generate-task-test.ts.snap
packages/cli/__tests__/generators/generate-task-test.ts
packages/cli/src/generators/task.ts

Fixes task generator to cleanup task imports and exports

---

packages/cli/__tests__/generators/__snapshots__/generate-plugin-test.ts.snap
packages/cli/__tests__/generators/generate-plugin-test.ts
packages/cli/src/generators/plugin.ts
packages/cli/templates/src/plugin/package.json.ejs
packages/cli/templates/src/plugin/tsconfig.json
packages/parser-eslint/package.json
packages/plugin-ember-octane/package.json
packages/plugin-ember/package.json

Fix plugin generator

---

packages/cli/__tests__/report-components/table-test.ts
packages/cli/src/static/components/table.hbs
packages/core/src/report-components/graded-table-data.ts
packages/core/src/report-components/table-data.ts
packages/core/src/types/index.ts

Implementing table UI component and added tests. Screenshot attached

Implementing table

---

packages/cli/__tests__/generators/__snapshots__/generate-plugin-test.ts.snap
packages/cli/__tests__/generators/__snapshots__/generate-task-test.ts.snap
packages/cli/templates/src/plugin/package.json.ejs
packages/cli/templates/src/task/src/results/task-result.js.ejs
packages/cli/templates/src/task/src/results/task-result.ts.ejs

The generators have drifted a bit out of date. This PR updates them.

Updating generators

---

README.md

Adding badges to top-level readme

---

packages/cli/__tests__/generators/__snapshots__/generate-config-test.ts.snap
packages/cli/__tests__/generators/generate-config-test.ts
packages/cli/src/commands/generate.ts
packages/cli/src/generators/config.ts
packages/core/__tests__/configuration/__snapshots__/checkup-config-service-test.ts.snap
packages/core/__tests__/configuration/checkup-config-service-test.ts
packages/core/src/configuration/checkup-config-service.ts
packages/core/src/types/configuration.ts

Simplification and cleanup of config generator.

Cleanup of config generator

---

packages/checkup-plugin-ember-octane/__tests__/results/__snapshots__/octane-migration-status-tast-result-test.ts.snap
packages/checkup-plugin-ember-octane/src/results/octane-migration-status-task-result.ts
packages/core/src/utils/ui.ts

Updated octane output to new format:

Updates output in octane task to be in bar format

---

packages/checkup-plugin-ember/__tests__/__snapshots__/ember-dependencies-task-test.ts.snap
packages/checkup-plugin-ember/__tests__/__snapshots__/ember-types-task-test.ts.snap
packages/checkup-plugin-ember/__tests__/ember-dependencies-task-test.ts
packages/checkup-plugin-ember/src/results/ember-dependencies-task-result.ts
packages/checkup-plugin-ember/src/results/ember-types-task-result.ts
packages/checkup-plugin-ember/src/tasks/ember-dependencies-task.ts
packages/checkup-plugin-ember/src/tasks/ember-types-task.ts
packages/core/package.json
packages/core/src/index.ts
packages/core/src/searchers/file-searcher.ts
packages/core/src/types/tasks.ts
packages/core/src/utils/data-transformers.ts
types/startcase.d.ts
yarn.lock

Standardizing and summarizing the Ember tasks.

Correctly summarizing output of ember tasks

---

package.json

Adding labels for checkup tasks and generators.

Adding more labels for publishing

---

packages/checkup-plugin-ember/__tests__/__snapshots__/ember-in-repo-addons-engines-task-test.ts.snap
packages/checkup-plugin-ember/__tests__/ember-in-repo-addons-engines-task-test.ts
packages/checkup-plugin-ember/src/hooks/register-tasks.ts
packages/checkup-plugin-ember/src/results/ember-in-repo-addons-engines-task-result.ts
packages/checkup-plugin-ember/src/tasks/ember-in-repo-addons-engines-task.ts
packages/cli/__tests__/generators/__snapshots__/generate-task-test.ts.snap
packages/cli/templates/src/task/__tests__/task.js.ejs
packages/cli/templates/src/task/__tests__/task.ts.ejs
packages/core/src/utils/get-package-json.ts
packages/test-helpers/src/ember-cli-fixturify-project.ts

Returns # engines and # addons
also fixed bug in generator fixture - missing parenthesis

[task] - number of Ember engines and addons

---

packages/cli/__tests__/commands/__snapshots__/run-test.ts.snap
packages/cli/__tests__/tasks/__snapshots__/outdated-dependencies-task-test.ts.snap
packages/cli/src/results/outdated-dependencies-task-result.ts
packages/core/src/utils/ui.ts

[task] Updates Outdated Dependency output to use barchart

---

packages/checkup-plugin-ember/__tests__/__snapshots__/ember-types-task-test.ts.snap
packages/cli/__tests__/commands/__snapshots__/run-test.ts.snap
packages/cli/__tests__/tasks/eslint-disable-task-test.ts
packages/cli/__tests__/tasks/todos-task-test.ts
packages/cli/package.json
packages/cli/src/commands/run.ts
packages/cli/src/results/eslint-disable-task-result.ts
packages/cli/src/tasks/eslint-disable-task.ts
packages/core/__tests__/searchers/file-searcher-test.ts
packages/test-helpers/src/filter-result-data.ts
yarn.lock

Adding task that counts the number of eslint overrides

Adding task that counts the number of eslint overrides

---

packages/checkup-plugin-javascript/__tests__/__snapshots__/eslint-summary-task-test.ts.snap
packages/checkup-plugin-javascript/__tests__/eslint-summary-task-test.ts
packages/checkup-plugin-javascript/src/hooks/register-tasks.ts
packages/checkup-plugin-javascript/src/results/eslint-summary-task-result.ts
packages/checkup-plugin-javascript/src/tasks/eslint-summary-task.ts
packages/core/src/parsers/eslint-parser.ts
packages/test-helpers/src/checkup-fixturify-project.ts

This run eslint as configured in the app checkup is being run on, and summarizes the results.

Adding task that runs eslint as configured in the app checkup is being run on

---

packages/cli/__tests__/task-result-comparator-test.ts
packages/cli/src/task-list.ts
packages/cli/src/task-result-comparator.ts
packages/core/src/types/tasks.ts

Sorting tasks by category, then group.

---

packages/cli/src/commands/generate.ts

Output correct generators list on missing generator

---

packages/core/src/types/ember-template-lint.ts

Extending ember-template-lint config type definition

---

packages/cli/package.json
packages/core/package.json
packages/core/src/utils/get-paths.ts
yarn.lock

closes https://github.com/checkupjs/checkup/issues/473

Bumping walksync and using new API to fix #473

---

packages/cli/src/commands/generate.ts
packages/cli/src/generators/config.ts
packages/cli/src/generators/plugin.ts
packages/cli/src/generators/task.ts
packages/core/src/config/index.ts

Error handling cleanup for generators. Additionally fixed a bug with plugin shortnames in config.

Fixes generator error handling. Fix bug with short plugin names

---

packages/checkup-plugin-ember/__tests__/__snapshots__/ember-test-type-task-test.ts.snap
packages/checkup-plugin-ember/package.json
packages/core/__tests__/utils/__snapshots__/ui-test.ts.snap
packages/core/__tests__/utils/ui-test.ts
packages/core/src/utils/ui.ts

*Motivation*
I was using sectionedBar in my task and it was resulting in funky output.

[tests] add tests and fixes sectionedBar calculations

---

packages/core/src/utils/ui.ts

[enhancement] use Number.prototype.toLocaleString() for bar and sectionedBar

---

packages/cli/__tests__/commands/__snapshots__/run-test.ts.snap
packages/cli/__tests__/generators/__snapshots__/generate-config-test.ts.snap
packages/cli/__tests__/tasks/checkup-meta-task-test.ts
packages/cli/src/meta-task-list.ts
packages/cli/src/task-list.ts
packages/core/__tests__/config-test.ts
packages/core/src/base-task.ts
packages/core/src/config/config-schema.json
packages/core/src/config/index.ts
packages/core/src/types/config.ts
packages/core/src/types/tasks.ts
packages/test-helpers/src/get-task-context.ts

Enhances config schema
- Updates schema to more specifically define the type required for tasks, including the task config
- Updates config generator to reference config schema to enable editor authoring support

Enhances config schema to correctly enforce task config

---

packages/checkup-plugin-ember/__tests__/__snapshots__/ember-in-repo-addons-engines-task-test.ts.snap
packages/checkup-plugin-ember/__tests__/ember-in-repo-addons-engines-task-test.ts
packages/checkup-plugin-ember/src/results/ember-dependencies-task-result.ts
packages/checkup-plugin-ember/src/results/ember-in-repo-addons-engines-task-result.ts
packages/checkup-plugin-ember/src/tasks/ember-dependencies-task.ts
packages/checkup-plugin-ember/src/tasks/ember-in-repo-addons-engines-task.ts

Partial implementation of https://github.com/checkupjs/rfcs/pull/1

Converting in-repo task to schema

---

packages/checkup-plugin-ember/__tests__/__snapshots__/ember-types-task-test.ts.snap
packages/checkup-plugin-ember/__tests__/ember-types-task-test.ts
packages/checkup-plugin-ember/__tests__/template-lint-disable-task-test.ts
packages/checkup-plugin-ember/src/results/ember-types-task-result.ts
packages/checkup-plugin-ember/src/tasks/ember-types-task.ts
packages/checkup-plugin-javascript/__tests__/eslint-disable-task-test.ts
packages/core/__tests__/searchers/file-searcher-test.ts
packages/test-helpers/src/filter-result-data.ts
packages/test-helpers/src/index.ts

Partial implementation of https://github.com/checkupjs/rfcs/pull/1

Converting ember types task to schema

---

packages/checkup-plugin-ember/__tests__/__snapshots__/ember-in-repo-addons-engines-task-test.ts.snap
packages/checkup-plugin-ember/__tests__/__snapshots__/ember-test-type-task-test.ts.snap
packages/checkup-plugin-ember/__tests__/ember-test-type-task-test.ts
packages/checkup-plugin-ember/__tests__/eslint-rule-tests/test-types.test.js
packages/checkup-plugin-ember/src/eslint/rules/test-types.js
packages/checkup-plugin-ember/src/results/ember-test-types-task-result.ts
packages/checkup-plugin-ember/src/tasks/ember-test-types-task.ts
packages/checkup-plugin-ember/src/utils/transformers.ts
packages/cli/__tests__/commands/__snapshots__/run-test.ts.snap
packages/cli/__tests__/tasks/lines-of-code-task-test.ts
packages/cli/src/commands/run.ts
packages/core/__tests__/config-test.ts
packages/core/src/builders.ts
packages/core/src/index.ts
packages/core/src/schemas/schema-utils.ts
packages/core/src/types/parsers.ts
packages/core/src/utils/data-transformers.ts
packages/core/src/utils/ui.ts

Partial implementation of checkupjs/rfcs#1

Convert ember test types to new schema

---

packages/checkup-plugin-ember-octane/tsconfig.json
packages/checkup-plugin-ember/tsconfig.json
packages/checkup-plugin-javascript/tsconfig.json
packages/cli/package.json
packages/cli/tsconfig.json
packages/core/tsconfig.json
packages/test-helpers/tsconfig.json
yarn.lock

Removes `@oclif/test` and explicit `type` configs in tsconfig.json.

Remove unneeded dependencies

---

packages/cli/src/commands/run.ts
packages/cli/src/task-list.ts
packages/core/src/types/cli.ts
packages/test-helpers/src/get-task-context.ts

Adding `--listTasks` flag to list all available tasks to run

---

packages/cli/__tests__/generators/__snapshots__/generate-plugin-test.ts.snap
packages/cli/__tests__/generators/generate-plugin-test.ts
packages/cli/src/generators/plugin.ts
packages/cli/templates/src/plugin/.eslintignore.ejs
packages/cli/templates/src/plugin/.eslintrc.js.ejs
packages/cli/templates/src/plugin/.eslintrc.ts.ejs
packages/cli/templates/src/plugin/.gitignore.ejs
packages/cli/templates/src/plugin/.prettierrc.js.ejs
packages/cli/templates/src/plugin/package.json.js.ejs
packages/cli/templates/src/plugin/package.json.ts.ejs

Add linting to plugins generated by plugin generator

---

packages/cli/__tests__/commands/__snapshots__/run-test.ts.snap
packages/cli/__tests__/commands/run-test.ts
packages/cli/__tests__/tasks/project-meta-task-test.ts
packages/cli/package.json
packages/cli/src/commands/run.ts
packages/cli/src/get-checkup-result.ts
packages/cli/src/reporters/console-reporter.ts
packages/cli/src/task-list.ts
packages/cli/src/tasks/project-meta-task.ts
packages/core/src/types/checkup-result.ts
yarn.lock

Adds task timings, exposed via setting an environment variable (`CHECKUP_TIMING=1`).

Adding task timings

---

packages/checkup-plugin-ember/__tests__/ember-template-lint-disable-task-test.ts
packages/checkup-plugin-ember/src/tasks/ember-template-lint-disable-task.ts
packages/checkup-plugin-javascript/__tests__/__snapshots__/outdated-dependencies-task-test.ts.snap
packages/checkup-plugin-javascript/__tests__/eslint-disable-task-test.ts
packages/checkup-plugin-javascript/__tests__/outdated-dependencies-task-test.ts
packages/checkup-plugin-javascript/src/actions/outdated-dependency-actions.ts
packages/checkup-plugin-javascript/src/tasks/eslint-disable-task.ts
packages/checkup-plugin-javascript/src/tasks/outdated-dependencies-task.ts
packages/cli/src/reporters/console-reporter.ts
packages/core/src/types/checkup-result.ts
packages/core/src/utils/ui.ts

This represents the first refactoring of the console reporter to auto-render results based on type.

First steps at standardizing console reporter - implementing SummaryResult reporters

---

.github/workflows/ci-build.yml
packages/checkup-plugin-ember-octane/package.json
yarn.lock

Bumping eslint-plugin-ember

---

packages/core/__tests__/config-test.ts
packages/core/src/config.ts

Adds more specific error message when the JSON in the config is invalid.

Expand error handling for invalid config files

---

.eslintrc
package.json
packages/core/src/types/checkup-result.ts
yarn.lock

https://stackoverflow.com/questions/57802057/eslint-configuring-no-unused-vars-for-typescript for context

Bumping @typescript-eslint/eslint-plugin

---

packages/checkup-plugin-ember-octane/README.md
packages/checkup-plugin-ember/README.md
packages/checkup-plugin-javascript/README.md

Fix minor styling issues in plugin READMEs

---

packages/cli/__tests__/commands/__snapshots__/info-test.ts.snap
packages/cli/__tests__/commands/__snapshots__/migration-test.ts.snap
packages/cli/src/reporters/verbose-console-reporter.ts

Only show total results summary if there is more than 1 bullet point (result) shown

Only conditionally show total results in verbose-reporter

---

packages/checkup-plugin-ember/src/tasks/ember-in-repo-addons-engines-task.ts
packages/checkup-plugin-javascript/__tests__/eslint-summary-task-test.ts
packages/checkup-plugin-javascript/src/tasks/eslint-summary-task.ts
packages/checkup-plugin-javascript/src/tasks/outdated-dependencies-task.ts
packages/cli/__tests__/task-list-test.ts
packages/cli/src/api/checkup-task-runner.ts
packages/cli/src/get-log.ts
packages/cli/src/reporters/get-reporter.ts
packages/cli/src/task-list.ts
packages/core/__tests__/config-test.ts
packages/core/src/config.ts
packages/core/src/data/sarif.ts
packages/core/src/errors/error-kind.ts
packages/core/src/errors/task-error.ts
packages/core/src/index.ts
packages/core/src/types/tasks.ts

Adds new `TaskError` class to provide more standardized task error output based on `CheckupError` semantics.

Adds TaskError class to provide to task implementers

---

packages/cli/__tests__/cli-test.ts

Removes warnings from yeoman in cli-tests.

Removes yeoman output in tests

---

package.json
packages/cli/__tests__/generators/__snapshots__/generate-task-test.ts.snap
packages/cli/templates/src/task/__tests__/task.js.ejs
packages/cli/templates/src/task/__tests__/task.ts.ejs
packages/test-helpers/src/filter-result-data.ts
packages/test-helpers/src/index.ts
yarn.lock

Removing unused old testing APIs from `@checkup/test-helpers`.

Removes unused APIs

---

packages/checkup-plugin-javascript/__tests__/eslint-disable-task-test.ts
packages/cli/__tests__/generators/__snapshots__/generate-plugin-test.ts.snap
packages/cli/templates/src/plugin/package.json.js.ejs
packages/cli/templates/src/plugin/package.json.ts.ejs

Correctly generates plugins with latest package versions

---

packages/cli/src/index.ts

Exports the `getReporter` APIs for programmatic usage.

Export reporter APIs

---

.eslintrc
package.json
packages/checkup-plugin-javascript/__tests__/eslint-disable-task-test.ts
packages/checkup-plugin-javascript/src/tasks/eslint-disable-task.ts
packages/cli/src/api/checkup-task-runner.ts
packages/cli/src/formatters/formatter-utils.ts
packages/cli/src/formatters/summary.ts
packages/cli/src/generators/actions.ts
packages/cli/src/generators/plugin.ts
packages/cli/src/generators/task.ts
packages/cli/src/task-list.ts
packages/core/src/errors/checkup-error.ts
packages/core/src/utils/console-writer.ts
packages/core/src/utils/get-paths.ts
packages/test-helpers/src/ember-cli-fixturify-project.ts
yarn.lock

There are a bunch of new rules here, I turned off a few I just don't agree with, open to potentially turning off a few more if there are concerns!

Bumping eslint-plugin-unicorn

---

packages/cli/__tests__/__snapshots__/cli-test.ts.snap
packages/cli/__tests__/cli-test.ts
packages/cli/src/checkup.ts

Fixes incorrectly parsing only a single path when multiple paths are passed.

Fixes paths parsing to include multiple paths

---

packages/checkup-plugin-ember/src/tasks/ember-template-lint-disable-task.ts
packages/checkup-plugin-javascript/src/tasks/eslint-disable-task.ts
packages/core/package.json
packages/core/src/analyzers/ast-analyzer.ts
packages/core/src/analyzers/handlebars-analyzer.ts
packages/core/src/index.ts
packages/plugin/src/generate-docs.ts
yarn.lock

Adding handlebars analyzer

---

packages/checkup-plugin-ember/src/tasks/ember-dependencies-task.ts
packages/checkup-plugin-ember/src/tasks/ember-in-repo-addons-engines-task.ts
packages/checkup-plugin-javascript/src/tasks/outdated-dependencies-task.ts

Standardizes output in preparation for new SarifBuilder.

Standardizing output in tasks: ember-in-repo-addons-engines-task

---

packages/checkup-plugin-ember/src/tasks/ember-dependencies-task.ts
packages/checkup-plugin-ember/src/tasks/ember-in-repo-addons-engines-task.ts
packages/checkup-plugin-ember/src/tasks/ember-octane-migration-status-task.ts
packages/checkup-plugin-ember/src/tasks/ember-template-lint-disable-task.ts
packages/checkup-plugin-ember/src/tasks/ember-template-lint-summary-task.ts
packages/checkup-plugin-ember/src/tasks/ember-test-types-task.ts
packages/checkup-plugin-ember/src/tasks/ember-types-task.ts
packages/checkup-plugin-javascript/src/tasks/eslint-disable-task.ts
packages/checkup-plugin-javascript/src/tasks/eslint-summary-task.ts
packages/checkup-plugin-javascript/src/tasks/outdated-dependencies-task.ts
packages/core/__tests__/base-task-test.ts

Ensure all tasks are retrofitted with their component type for rendering
issue: #1053

Retrofit components

---

packages/checkup-plugin-ember/__tests__/__snapshots__/ember-octane-migration-status-task-test.ts.snap
packages/checkup-plugin-ember/src/tasks/ember-dependencies-task.ts
packages/checkup-plugin-ember/src/tasks/ember-octane-migration-status-task.ts
packages/checkup-plugin-ember/src/tasks/ember-template-lint-disable-task.ts
packages/checkup-plugin-ember/src/tasks/ember-template-lint-summary-task.ts
packages/checkup-plugin-ember/src/tasks/ember-test-types-task.ts
packages/checkup-plugin-javascript/src/tasks/eslint-disable-task.ts
packages/checkup-plugin-javascript/src/tasks/eslint-summary-task.ts
packages/checkup-plugin-javascript/src/tasks/outdated-dependencies-task.ts
packages/core/__tests__/base-task-test.ts
packages/core/src/analyzers/dependency-analyzer.ts
packages/core/src/base-task.ts
packages/core/src/data/lint.ts
packages/core/src/types/dependency.ts
packages/core/src/types/tasks.ts

Adds endLine/endColumn to result range

---

packages/cli/__tests__/generators/__snapshots__/generate-task-test.ts.snap
packages/cli/__tests__/generators/generate-task-test.ts
packages/cli/src/generators/task.ts
packages/cli/templates/src/task/src/tasks/task.js.ejs
packages/cli/templates/src/task/src/tasks/task.ts.ejs

Add description to Task generator

---

packages/cli/src/checkup.ts

Adds strongly typed `yargs.Arguments` to run command.

Adding type to CLI options

---

packages/cli/src/api/checkup-task-runner.ts
packages/cli/src/formatters/get-formatter.ts
packages/core/src/types/cli.ts

- Add js doc for `CheckupTaskRunner` and `getFormatter`
- Remove `componentName` from `FormatterOptions`

Add js doc for cli export contents

---

package.json
packages/checkup-plugin-ember/package.json
packages/checkup-plugin-javascript/package.json
packages/cli/package.json
packages/core/package.json
packages/plugin/package.json
packages/test-helpers/package.json
yarn.lock

Adds `sort-package-json` and associated scripts.

Sort all package.json files

---

package.json
packages/checkup-formatter-pretty/jest.config.js
yarn.lock

Resolves this issue: https://github.com/openpgpjs/openpgpjs/issues/985
Cause: https://github.com/facebook/jest/issues/2549
Resolution: https://github.com/kayahr/jest-environment-node-single-context

fix: Fixes v8 error thrown when running pretty formatter tests

---

packages/checkup-plugin-javascript/src/tasks/eslint-disable-task.ts
packages/cli/__tests__/cli-test.ts
packages/core/__tests__/data/checkup-log-builder-test.ts
packages/core/package.json
yarn.lock

Fixes a few issues that snuck through the conversion.

Updates stylelint to resolve error and import using file extension

---

packages/cli/__tests__/__utils__/get-fixture.ts
packages/cli/__tests__/formatters/json-test.ts
packages/cli/__tests__/formatters/pretty-test.ts
packages/cli/__tests__/formatters/sonarqube-test.ts
packages/cli/__tests__/formatters/summary-test.ts
packages/cli/src/formatters/get-formatter.ts
packages/cli/src/formatters/sonarqube.ts
packages/core/src/base-task.ts
packages/core/src/types/tasks.ts

Run with:
```sh
checkup run . --format sonarqube
```

Adds formatter for SonarQube

---

packages/core/package.json
yarn.lock

This change bumps E-T-L to v5.

chore(deps): Bump ember-template-lint to 5.0.0
